export const UPDATE_FORMDATA = 'UPDATE_FORMDATA';
export const LOGIN = 'LOGIN';

export const FETCH_SINGLE_PRODUCT_DATA = 'FETCH_SINGLE_PRODUCT_DATA';
export const SET_SINGLE_PRODUCT_DATA = 'SET_SINGLE_PRODUCT_DATA';

export const ADD_TO_CART = 'ADD_TO_CART';

export const SET_TOKEN = 'SET_TOKEN';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const LOGOUT = 'LOGOUT';