export const UPDATE_FORMDATA = 'UPDATE_FORMDATA';

export const FETCH_SINGLE_PRODUCT_DATA = 'FETCH_SINGLE_PRODUCT_DATA';
export const SET_SINGLE_PRODUCT_DATA = 'SET_SINGLE_PRODUCT_DATA';

export const ADD_TO_CART = 'ADD_TO_CART';