import React from 'react'
import {Button, Flex, Text} from '@chakra-ui/react'
import CarouselMain from './CarouselMain'
import CarouselWithMultiSlides from './CarouselWithMultiSlides'
const  SectionSecond = () => {

  const multiSlides =[
    {
      "componentType": "comp_0000SDMC",
      "visible": true,
      "name": "Best Deals On Air Coolers",
      "isDealTimerComponent": false,
      "dealTimerDetails": null,
      "displayName": "Best Deals On Air Coolers",
      "viewAllUrl": "https://www.reliancedigital.in/page/aircoolers-sda?internal_source=HP&internal_medium=Product-Carousel&internal_campaign=aircoolers-sda",
      "bannerPosition": null,
      "banners": [
        
      ],
      "data": [
        {
          "name": "Havells Kace 75 GHRACAMF220 Desert Air Cooler with 75 Litres Capacity, White and Blue",
          "imageUrl": "/medias/Havells-Kace-75-Cooler-493692107-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyNTMwNHxpbWFnZS9qcGVnfGltYWdlcy9oMmIvaDQ0Lzk5NjMwMTc4MzA0MzAuanBnfDY1N2NhZTU4YTZhMzg4ZjJlNmVkYWIwY2IxZjJkZGViYmE1ZTc3MTYxMmU0MzVkMmRhNTdmOTk5M2ZmMmFmNTA",
          "altText": "Havells Kace 75 GHRACAMF220 Desert Air Cooler with 75 Litres Capacity, White and Blue",
          "url": "/havells-kace-75-ghracamf220-desert-air-cooler-with-75-litres-capacity-white-and-blue/p/493692107",
          "mrp": "17890",
          "sellingPrice": "11990",
          "discount": "33%(₹5,900)",
          "deal": false,
          "inStock": true,
          "hasPP": true,
          "teaserType": "Get 3 Jar Mixer Worth 2399 FREE",
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>Smellfree Honey Comb Pads</li>\n<li>75 Litres Capacity</li>\n<li>Overload Protection</li>\n<li>XXL Ice Compartment</li>\n<li>3 Side Chill Drip Technology</li>",
          "skuId": "493692107",
          "masterCategory": {
            "code": "S101511",
            "name": "Air Coolers",
            "url": "/air-coolers/c/S101511",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "KACE 75",
          "numberOfReviews": 4,
          "numberOfRatings": 6,
          "averageRating": 4.5,
          "fullReviewUrl": null
        },
        {
          "name": "Symphony Diet 3D 55i+ Desert Air Cooler, 55 Litre",
          "imageUrl": "/medias/Symphony-Diet-Air-Cooler-491666305-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w5MDE1fGltYWdlL2pwZWd8aW1hZ2VzL2g2OS9oYzcvOTk2ODQwMDMzNDg3OC5qcGd8MzM0N2I1Y2RlZmFiZjBmMTEwODgzNWJkZWVjNjY5ZmM5OGQ2OTNjNzRlMmRiMDVjNzAwZGFkNzM2MWZjMGI5OA",
          "altText": "Symphony Diet 3D 55i+ Desert Air Cooler, 55 Litre",
          "url": "/symphony-diet-3d-55i-desert-air-cooler-55-litre/p/491666305",
          "mrp": "13599",
          "sellingPrice": "12990",
          "discount": "4%(₹609)",
          "deal": false,
          "inStock": true,
          "hasPP": true,
          "teaserType": "Get 3 Jar Mixer Worth 2399 FREE",
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>For rooms up to 16 square meter</li><li>Large 55 Litres tank capacity</li><li>Consumes up to 145 watts only</li><li>Automatic pop-up touchscreen</li><li>3-side high efficiency honeycomb cooling pads</li><li>i-Pure technology</li><li>Magnetic remote</li><li>Multi directional wheels for mobility</li><li>Moderate Heat or Humid Climate</li>",
          "skuId": "491666305",
          "masterCategory": {
            "code": "S101511",
            "name": "Air Coolers",
            "url": "/air-coolers/c/S101511",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "DIET 3D - 55I+",
          "numberOfReviews": 4,
          "numberOfRatings": 10,
          "averageRating": 4.7,
          "fullReviewUrl": null
        },
        {
          "name": "Bajaj Shield Series Elevate 65 Desert Air Cooler",
          "imageUrl": "/medias/Bajaj-Air-Cooler-494338771-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wzMTA2M3xpbWFnZS9qcGVnfGltYWdlcy9oNzEvaDI1LzEwMTA4NzA2MDk1MTM0LmpwZ3xlOWZmZGI4ZDZiZDZhNjAzYWY3NjA1MjBlMGVlMzAzM2EzNTNhOTMxZTI2YzY5MDQ0ZjRhMDE4MmRhZTg2Y2Y2",
          "altText": "Bajaj Shield Series Elevate 65 Desert Air Cooler",
          "url": "/bajaj-shield-series-elevate-65-desert-air-cooler/p/494338771",
          "mrp": "18090",
          "sellingPrice": "11499",
          "discount": "36%(₹6,591)",
          "deal": false,
          "inStock": true,
          "hasPP": true,
          "teaserType": "Get 3 Jar Mixer Worth 2399 FREE",
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>DuraTuff PRO Motor & DuraMarine PRO Pump</li><li>Anti-bacterial Hexacool Master</li><li>Ice chamber on top</li><li>Powerful Air Throw</li><li>65 L Water Tank Capacity</li><li>Air Flow (CMH) - 5600</li><li>Pump Warranty - 3 years</li>",
          "skuId": "494338771",
          "masterCategory": {
            "code": "S101511",
            "name": "Air Coolers",
            "url": "/air-coolers/c/S101511",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "480151",
          "numberOfReviews": 1,
          "numberOfRatings": 1,
          "averageRating": 4.0,
          "fullReviewUrl": null
        },
        {
          "name": "Havells Kalt GHRACAAD008 Personal Air Cooler with 24 Litre Capacity, White and Brown",
          "imageUrl": "/medias/Havells-GHRACAAD008-Air-Cooler-492664512-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxOTU0NHxpbWFnZS9qcGVnfGltYWdlcy9oYzEvaDkzLzk5NjMwMTc1MDI3NTAuanBnfDA5YTk2N2I1MjY2MmYzYmU3MzhiODhiODUwNzcxZTNmYmU4MGY4MGQ1MWNjODhhMjQxZDBmOGEzZGQ3YzJmMmU",
          "altText": "Havells Kalt GHRACAAD008 Personal Air Cooler with 24 Litre Capacity, White and Brown",
          "url": "/havells-kalt-ghracaad008-personal-air-cooler-with-24-litre-capacity-white-and-brown/p/492664512",
          "mrp": "8790",
          "sellingPrice": "6199",
          "discount": "29%(₹2,591)",
          "deal": false,
          "inStock": true,
          "hasPP": true,
          "teaserType": "Get Iron FREE & 7.5% Discount",
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>Aerodynamically Designed Fan</li> \n<li>3 Side Smell Free Honeycomb Pad</li> \n<li>Optimum Air-Delivery</li> \n<li>24 Litres Tank Capacity</li> \n<li>Corrosion Resistance & Sturdy Design</li>",
          "skuId": "492664512",
          "masterCategory": {
            "code": "S101511",
            "name": "Air Coolers",
            "url": "/air-coolers/c/S101511",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "GHRACAAD008",
          "numberOfReviews": 2,
          "numberOfRatings": 8,
          "averageRating": 4.8,
          "fullReviewUrl": null
        },
        {
          "name": "Kenstar Desert Tall 105 L Air Cooler, DE HC105",
          "imageUrl": "/medias/Kenstar-Desert-Cooler-494338814-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxNDY5NHxpbWFnZS9qcGVnfGltYWdlcy9oZmQvaGE4LzEwMTEwNDYyMjMwNTU4LmpwZ3wyODNkNTE5NzZjZGExMGI5ZDg2OWFiMTVjYWZiOWQ3OGIwOGFkYjdhYTIyYmRhM2M4NTQxYTgxMDBhYzE2M2Vi",
          "altText": "Kenstar Desert Tall 105 L Air Cooler, DE HC105",
          "url": "/kenstar-desert-tall-105-l-air-cooler-de-hc105/p/494338814",
          "mrp": "18490",
          "sellingPrice": "11990",
          "discount": "35%(₹6,500)",
          "deal": false,
          "inStock": true,
          "hasPP": true,
          "teaserType": "Get 3 Jar Mixer Worth 2399 FREE",
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>105 Litre tank capacity </li><li>Manual</li><li>Honeycomb</li><li>Motorised louvers</li><li>18 inch fan</li><li>ice chamber</li><li>Air Flow (CMH) - 4200</li>\n<li>Pump Warranty - 12 months</li>",
          "skuId": "494338814",
          "masterCategory": {
            "code": "S101511",
            "name": "Air Coolers",
            "url": "/air-coolers/c/S101511",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "KCLTLDWH105FMH-ESV",
          "numberOfReviews": 0,
          "numberOfRatings": 0,
          "averageRating": 0.0,
          "fullReviewUrl": null
        },
        {
          "name": "Symphony Sumo 75XL Desert Air Cooler with i-Pure technology, 75 Litres",
          "imageUrl": "/medias/Symphony-75XL-Air-Cooler-491666297-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxMTYxMXxpbWFnZS9qcGVnfGltYWdlcy9oYzMvaDAzLzk5NjgzODg5NjQzODIuanBnfDc2YjAwNjgwMzc3OTY5NTk4NzM2ZmRjMjRkNWNkMjQyMDgzNDBmY2NkNzEzOTY4MTMyMjJkYTg4YzJlNWZlMGI",
          "altText": "Symphony Sumo 75XL Desert Air Cooler with i-Pure technology, 75 Litres",
          "url": "/symphony-sumo-75xl-desert-air-cooler-with-i-pure-technology-75-litres/p/491666297",
          "mrp": "15499",
          "sellingPrice": "13990",
          "discount": "10%(₹1,509)",
          "deal": false,
          "inStock": true,
          "hasPP": true,
          "teaserType": "Get 3 Jar Mixer Worth 2399 FREE",
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>For rooms up to 37 square meter</li>\n<li>High efficiency honeycomb cooling pads</li>\n<li>i-Pure technology</li>\n<li>Cool flow dispenser</li>\n<li>Multi directional wheels for mobility</li>",
          "skuId": "491666297",
          "masterCategory": {
            "code": "S101511",
            "name": "Air Coolers",
            "url": "/air-coolers/c/S101511",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "SUMO 75 XL",
          "numberOfReviews": 1,
          "numberOfRatings": 9,
          "averageRating": 4.8,
          "fullReviewUrl": null
        },
        {
          "name": "Havells Zurii 55 Tower Air Cooler",
          "imageUrl": "/medias/Havells-Air-Cooler-494338763-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxOTEyN3xpbWFnZS9qcGVnfGltYWdlcy9oM2QvaGJjLzEwMTA4NzAzMDgwNDc4LmpwZ3w3NjE1ZTY2ZjQ3YzkyOTY1MTJkODI5ZmFkNzY1OGEzYzA5OTA4MTJkNzMyNjA2NjE4ODRiNGI2ODZiMmYyYjg4",
          "altText": "Havells Zurii 55 Tower Air Cooler",
          "url": "/havells-zurii-55-tower-air-cooler/p/494338763",
          "mrp": "17690",
          "sellingPrice": "11499",
          "discount": "35%(₹6,191)",
          "deal": false,
          "inStock": true,
          "hasPP": true,
          "teaserType": "Get 3 Jar Mixer Worth 2399 FREE",
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>55 L Tank Capacity</li><li>Powerful Air-Delivery of 1250 m3/hr</li><li>Electronic Panel & Remote</li><li>Ionizer [Active Purification]</li><li>Completely Collapsible Louvers</li>",
          "skuId": "494338763",
          "masterCategory": {
            "code": "S101511",
            "name": "Air Coolers",
            "url": "/air-coolers/c/S101511",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "ZURII 55",
          "numberOfReviews": 0,
          "numberOfRatings": 0,
          "averageRating": 0.0,
          "fullReviewUrl": null
        },
        {
          "name": "Symphony Diet 50T Tower Air Cooler, 50 Litres",
          "imageUrl": "/medias/Symphony-Diet-50T-Air-Cooler-490555337-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w0Mzg4fGltYWdlL2pwZWd8aW1hZ2VzL2hlNi9oM2YvMTAxMTAyMTc0NTM1OTguanBnfGIzODQzNGUzNTE4NGE4MTc5ZGEwYmFjYmI2NDFmNDZhMmU4MmI4MDVmMDA1MTZmZTBiYjgzZjg3ZTg3NDJhYjA",
          "altText": "Symphony Diet 50T Tower Air Cooler, 50 Litres",
          "url": "/symphony-diet-50t-tower-air-cooler-50-litres/p/490555337",
          "mrp": "12999",
          "sellingPrice": "8890",
          "discount": "32%(₹4,109)",
          "deal": false,
          "inStock": true,
          "hasPP": true,
          "teaserType": "Get Trimmer FREE & 7.5% Discount",
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>Powerful Blower</li> <li>I pure Technology</li> <li>Honeycomb Pads</li> <li>Easy Mobility</li> <li>Cool Flow Dispenser</li>",
          "skuId": "490555337",
          "masterCategory": {
            "code": "S101511",
            "name": "Air Coolers",
            "url": "/air-coolers/c/S101511",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": null,
          "numberOfReviews": 2,
          "numberOfRatings": 2,
          "averageRating": 5.0,
          "fullReviewUrl": null
        },
        {
            "name": "Havells Kace 75 GHRACAMF220 Desert Air Cooler with 75 Litres Capacity, White and Blue",
            "imageUrl": "/medias/Havells-Kace-75-Cooler-493692107-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyNTMwNHxpbWFnZS9qcGVnfGltYWdlcy9oMmIvaDQ0Lzk5NjMwMTc4MzA0MzAuanBnfDY1N2NhZTU4YTZhMzg4ZjJlNmVkYWIwY2IxZjJkZGViYmE1ZTc3MTYxMmU0MzVkMmRhNTdmOTk5M2ZmMmFmNTA",
            "altText": "Havells Kace 75 GHRACAMF220 Desert Air Cooler with 75 Litres Capacity, White and Blue",
            "url": "/havells-kace-75-ghracamf220-desert-air-cooler-with-75-litres-capacity-white-and-blue/p/493692107",
            "mrp": "17890",
            "sellingPrice": "11990",
            "discount": "33%(₹5,900)",
            "deal": false,
            "inStock": true,
            "hasPP": true,
            "teaserType": "Get 3 Jar Mixer Worth 2399 FREE",
            "preOrderEnabled": false,
            "preOrderDetails": null,
            "summary": "<li>Smellfree Honey Comb Pads</li>\n<li>75 Litres Capacity</li>\n<li>Overload Protection</li>\n<li>XXL Ice Compartment</li>\n<li>3 Side Chill Drip Technology</li>",
            "skuId": "493692107",
            "masterCategory": {
              "code": "S101511",
              "name": "Air Coolers",
              "url": "/air-coolers/c/S101511",
              "description": null,
              "image": null,
              "parentCategoryName": null,
              "sequence": 0
            },
            "productModelName": "KACE 75",
            "numberOfReviews": 4,
            "numberOfRatings": 6,
            "averageRating": 4.5,
            "fullReviewUrl": null
          },
          {
            "name": "Symphony Diet 3D 55i+ Desert Air Cooler, 55 Litre",
            "imageUrl": "/medias/Symphony-Diet-Air-Cooler-491666305-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w5MDE1fGltYWdlL2pwZWd8aW1hZ2VzL2g2OS9oYzcvOTk2ODQwMDMzNDg3OC5qcGd8MzM0N2I1Y2RlZmFiZjBmMTEwODgzNWJkZWVjNjY5ZmM5OGQ2OTNjNzRlMmRiMDVjNzAwZGFkNzM2MWZjMGI5OA",
            "altText": "Symphony Diet 3D 55i+ Desert Air Cooler, 55 Litre",
            "url": "/symphony-diet-3d-55i-desert-air-cooler-55-litre/p/491666305",
            "mrp": "13599",
            "sellingPrice": "12990",
            "discount": "4%(₹609)",
            "deal": false,
            "inStock": true,
            "hasPP": true,
            "teaserType": "Get 3 Jar Mixer Worth 2399 FREE",
            "preOrderEnabled": false,
            "preOrderDetails": null,
            "summary": "<li>For rooms up to 16 square meter</li><li>Large 55 Litres tank capacity</li><li>Consumes up to 145 watts only</li><li>Automatic pop-up touchscreen</li><li>3-side high efficiency honeycomb cooling pads</li><li>i-Pure technology</li><li>Magnetic remote</li><li>Multi directional wheels for mobility</li><li>Moderate Heat or Humid Climate</li>",
            "skuId": "491666305",
            "masterCategory": {
              "code": "S101511",
              "name": "Air Coolers",
              "url": "/air-coolers/c/S101511",
              "description": null,
              "image": null,
              "parentCategoryName": null,
              "sequence": 0
            },
            "productModelName": "DIET 3D - 55I+",
            "numberOfReviews": 4,
            "numberOfRatings": 10,
            "averageRating": 4.7,
            "fullReviewUrl": null
          }
          
      ]
    },
    {
      "componentType": "comp_0000S9RB",
      "visible": true,
      "name": "2024 New Range of ACs from Rs. 22990*",
      "isDealTimerComponent": false,
      "dealTimerDetails": null,
      "displayName": "2024 New Range of ACs from Rs. 22990*",
      "viewAllUrl": "[3:29 PM] Priyanshu Chalana https://www.reliancedigital.in/search?q=:relevance:productTags:AC-New-Launches-2024:availability:Exclude%20out%20of%20Stock&page=0&internal_source=HP&internal_medium=Product-Carousel&internal_campaign=AC-New-Launches-2024",
      "bannerPosition": null,
      "banners": [
        
      ],
      "data": [
        {
          "name": "SAMSUNG 1.5 Ton 3 Star  5 in1 Convertible Inverter Split AC, AR18CY3ZAWK (HD Filter,100% Copper, R32, 2024 launch)",
          "imageUrl": "/medias/Samsung-Convertible-5-in-1-Inverter-Split-AC-581110576-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w3MTE3fGltYWdlL2pwZWd8aW1hZ2VzL2gyZS9oNTYvMTAwOTg2MDc4NDk1MDIuanBnfDViYWJhOWQ1OGQwMDYzZDBkMGM3ZmZmZjI5ZjFkZjlkNzZhMTQ4Zjg1NmFhMGQ0OWVjZGRlY2VkM2IwZjk2NzI",
          "altText": "SAMSUNG 1.5 Ton 3 Star  5 in1 Convertible Inverter Split AC, AR18CY3ZAWK (HD Filter,100% Copper, R32, 2024 launch)",
          "url": "/samsung-1-5-ton-3-star-5-in1-convertible-inverter-split-ac-ar18cy3zawk-hd-filter-100-copper-r32-2024-launch-/p/581110576",
          "mrp": "60990",
          "sellingPrice": "38990",
          "discount": "36%(₹22,000)",
          "deal": false,
          "inStock": true,
          "hasPP": false,
          "teaserType": null,
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>5 in 1 Convertible</li>\n<li>HD Filter</li>\n<li>2 Way Auto Swing</li>\n<li>100% Copper Condensor</li>",
          "skuId": "581110576",
          "masterCategory": {
            "code": "S10151010",
            "name": "Split Air Conditioners",
            "url": "/split-air-conditioners/c/S10151010",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "AR18CY3ZAWKNNA",
          "numberOfReviews": 0,
          "numberOfRatings": 0,
          "averageRating": 0.0,
          "fullReviewUrl": null
        },
        {
          "name": "SAMSUNG 1.5 Ton 5 Star Wifi Inverter Split AC, AR18CY5AMWK (WindFree Technology, PM2.5, 4 Way Auto Swing,100% Copper , Freeze Wash , 2024 launch)",
          "imageUrl": "/medias/Samsung-WindFree-Inverter-Split-Air-Conditioner-581110398-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxMDM0NHxpbWFnZS9qcGVnfGltYWdlcy9oYjkvaDRlLzEwMDk4NjA5NDg3OTAyLmpwZ3xiNTBkMjQ2Njg1ZmY5NTFjMzQ2NmNhNGE4MmU1NjdiMjQ3ZWQyOTI5OWVlYTk5NzY3MDNmMTViN2E1NWFkZTA0",
          "altText": "SAMSUNG 1.5 Ton 5 Star Wifi Inverter Split AC, AR18CY5AMWK (WindFree Technology, PM2.5, 4 Way Auto Swing,100% Copper , Freeze Wash , 2024 launch)",
          "url": "/samsung-1-5-ton-5-star-wifi-inverter-split-ac-ar18cy5amwk-windfree-technology-pm2-5-4-way-auto-swing-100-copper-freeze-wash-2024-launch-/p/581110398",
          "mrp": "75990",
          "sellingPrice": "53490",
          "discount": "30%(₹22,500)",
          "deal": false,
          "inStock": true,
          "hasPP": false,
          "teaserType": null,
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>WindFree Technology</li>\n<li>PM 2.5 Filter, Freez Wash</li>\n<li>WiFi +  AI Energy Mode,</li>\n<li>4 Way Auto Swing</li>\n<li>100% Copper Condensor</li>",
          "skuId": "581110398",
          "masterCategory": {
            "code": "S10151010",
            "name": "Split Air Conditioners",
            "url": "/split-air-conditioners/c/S10151010",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "AR18CY5AMWK",
          "numberOfReviews": 2,
          "numberOfRatings": 2,
          "averageRating": 5.0,
          "fullReviewUrl": null
        },
        {
          "name": "SAMSUNG 1.5 Ton 3 Star Wifi Inverter Spilt AC, AR18CY3ANWK (WindFree Technology, PM 2.5 Filter, WiFi , 4 WayAuto Swing, 100% Copper, 2024 launch)",
          "imageUrl": "/medias/Samsung-WindFree-Inverter-Split-Air-Conditioner-581110575-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxMTk2M3xpbWFnZS9qcGVnfGltYWdlcy9oYzUvaGI2LzEwMDk4NjA4ODMyNTQyLmpwZ3wxNjVjNWQ5ZmFiNjA0NGQ0MGU5MWI1YTIyOWMzNmEyZGM5Y2RlZWIxMGY1ZTIyYmE4YmM3YmY1NTEyMjgxYzIz",
          "altText": "SAMSUNG 1.5 Ton 3 Star Wifi Inverter Spilt AC, AR18CY3ANWK (WindFree Technology, PM 2.5 Filter, WiFi , 4 WayAuto Swing, 100% Copper, 2024 launch)",
          "url": "/samsung-1-5-ton-3-star-wifi-inverter-spilt-ac-ar18cy3anwk-windfree-technology-pm-2-5-filter-wifi-4-wayauto-swing-100-copper-2024-launch-/p/581110575",
          "mrp": "64990",
          "sellingPrice": "43990",
          "discount": "32%(₹21,000)",
          "deal": false,
          "inStock": true,
          "hasPP": false,
          "teaserType": null,
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>Hot & Cold</li>\n<li>HD Filter</li>\n<li>2 Way Auto Swing</li>\n<li>100% Copper Condensor</li>",
          "skuId": "581110575",
          "masterCategory": {
            "code": "S10151010",
            "name": "Split Air Conditioners",
            "url": "/split-air-conditioners/c/S10151010",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "AR18CY3ANWKNNA",
          "numberOfReviews": 0,
          "numberOfRatings": 0,
          "averageRating": 0.0,
          "fullReviewUrl": null
        },
        {
          "name": "SAMSUNG 1.5 Ton 5Star 5 in 1 Convertible Inverter Spilt AC, AR18CY5ZAWK (HD Filter,100% Copper, R32, 2024 launch)",
          "imageUrl": "/medias/Samsung-Convertible-Inverter-Split-Air-Conditioner-581110577-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w3MTc4fGltYWdlL2pwZWd8aW1hZ2VzL2g5Mi9oZGQvMTAwOTg2MTAxNDMyNjIuanBnfDdhN2NlNWU1MmE3OGI3NjBmZGM2ZTE0ZDIxOGZjZTdkOGI1OGYxYzc1OTA2Y2E2MWRhMTgyNjI1ODc5ZDcwNzA",
          "altText": "SAMSUNG 1.5 Ton 5Star 5 in 1 Convertible Inverter Spilt AC, AR18CY5ZAWK (HD Filter,100% Copper, R32, 2024 launch)",
          "url": "/samsung-1-5-ton-5star-5-in-1-convertible-inverter-spilt-ac-ar18cy5zawk-hd-filter-100-copper-r32-2024-launch-/p/581110577",
          "mrp": "71990",
          "sellingPrice": "48990",
          "discount": "32%(₹23,000)",
          "deal": false,
          "inStock": true,
          "hasPP": false,
          "teaserType": null,
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>5 in 1 Convertible</li>\n<li>HD Filter</li>\n<li>2 Way Auto Swing</li>\n<li>100% Copper Condensor</li>",
          "skuId": "581110577",
          "masterCategory": {
            "code": "S10151010",
            "name": "Split Air Conditioners",
            "url": "/split-air-conditioners/c/S10151010",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "AR18CY5ZAWKNNA",
          "numberOfReviews": 0,
          "numberOfRatings": 0,
          "averageRating": 0.0,
          "fullReviewUrl": null
        },
        {
          "name": "Bluestar 1.5 Ton 5 Star 5 in 1 Convertible Inverter Split AC, IC518RNU (100 percent Copper, Smart Ready, Blue Fins Protection, Comfort Sleep, 2023 Launch)",
          "imageUrl": "/medias/Bluestar-IC518RNU-Air-Conditioner-581110409-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxMzI2NnxpbWFnZS9qcGVnfGltYWdlcy9oMDMvaGM1Lzk5NjgzMjI2MDkxODIuanBnfGYyZDlhMzMyNTFlODg4NzBmYWU4NmQ3NTMzZWQ3N2ZiMmU3YWUxYTQ0MzAzZGU3MWQyMThjMDVjZTg0Y2Q0ZTk",
          "altText": "Bluestar 1.5 Ton 5 Star 5 in 1 Convertible Inverter Split AC, IC518RNU (100 percent Copper, Smart Ready, Blue Fins Protection, Comfort Sleep, 2023 Launch)",
          "url": "/bluestar-1-5-ton-5-star-5-in-1-convertible-inverter-split-ac-ic518rnu-100-percent-copper-smart-ready-blue-fins-protection-comfort-sleep-2023-launch-/p/581110409",
          "mrp": "73000",
          "sellingPrice": "46990",
          "discount": "36%(₹26,010)",
          "deal": false,
          "inStock": true,
          "hasPP": false,
          "teaserType": null,
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>Turbo Cool</li>\n<li>5-in-1 Convertible Cooling</li>\n<li>Smart Ready</li>\n<li>100 Percent Copper</li>\n<li>Anti Corrosive Blue Fins for Protection</li>\n<li>Acoustic Jacket Around Compressor</li>\n<li>Comfort Sleep</li>",
          "skuId": "581110409",
          "masterCategory": {
            "code": "S10151010",
            "name": "Split Air Conditioners",
            "url": "/split-air-conditioners/c/S10151010",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "IC518RNU",
          "numberOfReviews": 0,
          "numberOfRatings": 1,
          "averageRating": 3.0,
          "fullReviewUrl": null
        },
        {
          "name": "Bluestar 1.5 Ton 5 Star 5 in 1 Convertible Inverter Split AC, IC518NNURS, 4 Way Swing, PM 2.5 Filter, Nano Blu Protect Technology, Smart AC with Smart App, 2024 Launch",
          "imageUrl": "/medias/Bluestar-SAC-15T-5SINV-IC518NNURS-581110654-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wzMTc0fGltYWdlL2pwZWd8aW1hZ2VzL2hmZi9oMDUvMTAxMDkzNzYzNjQ1NzQuanBnfDRmYTFjZjllZjY1Nzc2MDNiYzE3ZmI4ZjhhNDhkODM5ZmU1MmMyM2Y5YzI3OTIxMmMzNTQxZmNiN2RlY2E4NzM",
          "altText": "Bluestar 1.5 Ton 5 Star 5 in 1 Convertible Inverter Split AC, IC518NNURS, 4 Way Swing, PM 2.5 Filter, Nano Blu Protect Technology, Smart AC with Smart App, 2024 Launch",
          "url": "/bluestar-1-5-ton-5-star-5-in-1-convertible-inverter-split-ac-ic518nnurs-4-way-swing-pm-2-5-filter-nano-blu-protect-technology-smart-ac-with-smart-app-2024-launch/p/581110654",
          "mrp": "75500",
          "sellingPrice": "47990",
          "discount": "36%(₹27,510)",
          "deal": false,
          "inStock": true,
          "hasPP": false,
          "teaserType": null,
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>Smart AC with Smart App-Your Blue Star Smart AC</li>\n<li>Customised Sleep</li>\n<li>AI Pro</li>\n<li>5-in-1 Convertible</li>\n<li>Smart Scheduler</li>\n<li>PM2.5 Anti-Microbial Filter with Activated Carbon</li>\n<li>4-Way Swing</li>\n<li>Nano Blu Protect Technology</li>",
          "skuId": "581110654",
          "masterCategory": {
            "code": "S10151010",
            "name": "Split Air Conditioners",
            "url": "/split-air-conditioners/c/S10151010",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "IC518NNURS",
          "numberOfReviews": 0,
          "numberOfRatings": 0,
          "averageRating": 0.0,
          "fullReviewUrl": null
        },
        {
          "name": "BLUESTAR 1.5 Ton 3 Star 5 in 1 convertible Inverter Split AC -IC318MNU (100% copper, 4 way swing, Cooling Mode, Turbo Cool, Comfort sleep, 2023 launch)",
          "imageUrl": "/medias/BLUESTAR-IC318MNU-Split-Air-conditioner-581110331-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxODkxOHxpbWFnZS9qcGVnfGltYWdlcy9oYTgvaGNmLzk5NjUzNTkwNzEyNjIuanBnfDAxNzkwMDUxMGQyYjUzYjkwNmZiMTcxYjA2ZGQwNmNkMzc0ZjU0NWE0YTU4ZWU1ZDJkNmJlZDNkZWE5NjU1Y2M",
          "altText": "BLUESTAR 1.5 Ton 3 Star 5 in 1 convertible Inverter Split AC -IC318MNU (100% copper, 4 way swing, Cooling Mode, Turbo Cool, Comfort sleep, 2023 launch)",
          "url": "/bluestar-1-5-ton-3-star-5-in-1-convertible-inverter-split-ac--ic318mnu-100-copper-4-way-swing-cooling-mode-turbo-cool-comfort-sleep-2023-launch-/p/581110331",
          "mrp": "63500",
          "sellingPrice": "39490",
          "discount": "38%(₹24,010)",
          "deal": false,
          "inStock": true,
          "hasPP": false,
          "teaserType": null,
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>3 Star Split Air Conditioner</li>\n<li>5 in 1 Convertible Cooling Mode</li>\n<li>Turbo Cool - Powerful Mode</li>\n<li>Brushless DC Motor (BLDC)</li>",
          "skuId": "581110331",
          "masterCategory": {
            "code": "S10151010",
            "name": "Split Air Conditioners",
            "url": "/split-air-conditioners/c/S10151010",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "IC318MNU",
          "numberOfReviews": 0,
          "numberOfRatings": 1,
          "averageRating": 5.0,
          "fullReviewUrl": null
        },
        {
          "name": "Hitachi 1.5 Ton 3 Star Inverter Split AC, G318PCBISF ,Frost Wash, Hexa Sensor, Backlight Remocon, Tropical Design, 100% Copper, 2024 Launch",
          "imageUrl": "/medias/Hitachi-Split-AC-581110651-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxMzU2NHxpbWFnZS9qcGVnfGltYWdlcy9oNTUvaGYzLzEwMTA2NzM3OTUwNzUwLmpwZ3wzNDZjNGEyOThmZWM0NWVmOTE0MWVhNTI1YjhjOWIxZjhmNTg5MTQzZTY3NTdiZWFiYzg0Zjg1M2ZjMTU0NWM4",
          "altText": "Hitachi 1.5 Ton 3 Star Inverter Split AC, G318PCBISF ,Frost Wash, Hexa Sensor, Backlight Remocon, Tropical Design, 100% Copper, 2024 Launch",
          "url": "/hitachi-1-5-ton-3-star-inverter-split-ac-g318pcbisf-frost-wash-hexa-sensor-backlight-remocon-tropical-design-100-copper-2024-launch/p/581110651",
          "mrp": "63100",
          "sellingPrice": "37490",
          "discount": "41%(₹25,610)",
          "deal": false,
          "inStock": true,
          "hasPP": false,
          "teaserType": null,
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>Ice Clean (FrostWash) </li>\n<li>Surround Cooling (Long Air throw) </li>\n<li>My Mode </li>\n<li>Hexa Sensor Superfine Mesh filter</li>\n<li>Inner Grooved Copper tropical design</li>\n<li>Backlight Remocon</li>\n<li>Auto fan speed</li>\n<li>Auto Mode, 100% Copper, 43 Quality Test </li>\n<li>Dry Mode (Dehumidification)</li>",
          "skuId": "581110651",
          "masterCategory": {
            "code": "S10151010",
            "name": "Split Air Conditioners",
            "url": "/split-air-conditioners/c/S10151010",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "RAS.G318PCBISF",
          "numberOfReviews": 1,
          "numberOfRatings": 1,
          "averageRating": 5.0,
          "fullReviewUrl": null
        },
        {
          "name": "Hitachi 1.5 Ton 5 Star Inverter Split AC, G518PCBISF ,Frost Wash, Superfine Mesh Filter, 100% Copper, Tropical Design, 2024 Launch",
          "imageUrl": "/medias/Hitachi-Split-AC-581110646-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxMzU2NHxpbWFnZS9qcGVnfGltYWdlcy9oM2YvaDBiLzEwMTA2NzMxMDY5NDcwLmpwZ3w0M2Y4NTgwNGM5ZmI0ODdiZTYxZjZjYjU4MTVhYzc2YzQ0NTliM2MwYjkxZWE0ODBjMGM2MzE2Mjc1ZTcwZjQ2",
          "altText": "Hitachi 1.5 Ton 5 Star Inverter Split AC, G518PCBISF ,Frost Wash, Superfine Mesh Filter, 100% Copper, Tropical Design, 2024 Launch",
          "url": "/hitachi-1-5-ton-5-star-inverter-split-ac-g518pcbisf-frost-wash-superfine-mesh-filter-100-copper-tropical-design-2024-launch/p/581110646",
          "mrp": "74100",
          "sellingPrice": "44990",
          "discount": "39%(₹29,110)",
          "deal": false,
          "inStock": true,
          "hasPP": false,
          "teaserType": null,
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>Ice Clean (FrostWash) </li>\n<li>Surround Cooling (Long Air throw) </li>\n<li>My Mode </li>\n<li>Hexa Sensor Superfine Mesh filter</li>\n<li>Inner Grooved Copper tropical design</li>\n<li>Backlight Remocon</li>\n<li>Auto fan speed</li>\n<li>Auto Mode, 100% Copper, 43 Quality Test </li>\n<li>Dry Mode (Dehumidification)</li>",
          "skuId": "581110646",
          "masterCategory": {
            "code": "S10151010",
            "name": "Split Air Conditioners",
            "url": "/split-air-conditioners/c/S10151010",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "RAS.G518PCBISF",
          "numberOfReviews": 0,
          "numberOfRatings": 0,
          "averageRating": 0.0,
          "fullReviewUrl": null
        },
        {
          "name": "Gangnam 1.5 Ton 3 Star Inverter Split AC, 5 in 1 Convertible, Hydrophilic Blue fin, 100 percent Copper, GGINS18K3S23E",
          "imageUrl": "/medias/Gangnam-Inverter-Split-AC-581110668-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxNzcwMHxpbWFnZS9qcGVnfGltYWdlcy9oNjYvaDI4LzEwMTExNDczNjE0ODc4LmpwZ3wzZTA5YWVkZDYzMmYxNGFlOTdhZjQxNzU4MGU5MDJiZTJmYmI1MmRmYTg2MDFiNzU5NzY4NzY1NjFlOGQ4ODc5",
          "altText": "Gangnam 1.5 Ton 3 Star Inverter Split AC, 5 in 1 Convertible, Hydrophilic Blue fin, 100 percent Copper, GGINS18K3S23E",
          "url": "/gangnam-1-5-ton-3-star-inverter-split-ac-5-in-1-convertible-hydrophilic-blue-fin-100-percent-copper-ggins18k3s23e/p/581110668",
          "mrp": "44000",
          "sellingPrice": "26990",
          "discount": "39%(₹17,010)",
          "deal": false,
          "inStock": true,
          "hasPP": false,
          "teaserType": null,
          "preOrderEnabled": false,
          "preOrderDetails": null,
          "summary": "<li>5 in 1 Convertible</li>\n<li>Hydrophilic Blue fin</li>\n<li>100 percent Copper</li>",
          "skuId": "581110668",
          "masterCategory": {
            "code": "S10151010",
            "name": "Split Air Conditioners",
            "url": "/split-air-conditioners/c/S10151010",
            "description": null,
            "image": null,
            "parentCategoryName": null,
            "sequence": 0
          },
          "productModelName": "GGINS18K3S23E",
          "numberOfReviews": 0,
          "numberOfRatings": 0,
          "averageRating": 0.0,
          "fullReviewUrl": null
        }
      ]
    }
  ]
  const slideNumberOne_data = multiSlides[0].data;
  const slideNumberTwo_data = multiSlides[1].data;
  return (
    <Flex w={'100%'} >

        <Flex w={'100%'} justifyContent={'center'} alignItems={'center'} direction={'column'} gap={'5px'}>
           <Flex w={'100%'} bg={'#F9F9F9'} justifyContent={'center'} fontWeight={'500'}>
            <Flex justifyContent={'left'} w={'95%'} p={'20px 0px'} gap={'10px'}>
                    <Text>Best Deals On Air Coolers</Text>
                    <Button borderRadius={'revert'} fontSize={'xs'} color={'white'} bg={'#003380'}size={'sm'} p={'0px 10px'} _hover={{bg:'3003380', color:'white'}}>View All</Button>
                </Flex>
           </Flex>

            <Flex w={'100%'}   justifyContent={'center'} alignItems={'center'} >
             <CarouselWithMultiSlides multiSlidesData={slideNumberOne_data} />
            </Flex>

            <Flex w={'100%'} bg={'#F9F9F9'} justifyContent={'center'} fontWeight={'500'}>
            <Flex justifyContent={'left'} w={'95%'} p={'20px 0px'} gap={'10px'}>
                    <Text>2024 New Range of ACs from Rs. 22990*</Text>
                    <Button borderRadius={'revert'} fontSize={'xs'} color={'white'} bg={'#003380'}size={'sm'} p={'0px 10px'} _hover={{bg:'3003380', color:'white'}}>View All</Button>
                </Flex>
           </Flex>

           <Flex w={'100%'}   justifyContent={'center'} alignItems={'center'} >
             <CarouselWithMultiSlides multiSlidesData={slideNumberTwo_data} />
            </Flex>

 
        </Flex>    
    </Flex>
  )
}

export default SectionSecond