import { Button, Flex, Text } from '@chakra-ui/react';
import React from 'react'
import CarouselWithMultiSlides from './CarouselWithMultiSlides';

const SectionThree = () => {

    const mySlides = [
        {
          "componentType": "comp_0000SOET",
          "visible": true,
          "name": "Stock clearance Sale | Monitors starting from Rs.3299",
          "isDealTimerComponent": false,
          "dealTimerDetails": null,
          "displayName": "Stock clearance Sale | Monitors starting from Rs.3299",
          "viewAllUrl": "https://www.reliancedigital.in/search?q=:relevance:productTags:monitors-stock-clearance:availability:Exclude out of Stock&page=0&internal_source=HP&internal_medium=Product-Carousel&internal_campaign=monitors-stock-clearance",
          "bannerPosition": null,
          "banners": [
            
          ],
          "data": [
            {
              "name": "Acer EK220Q 54.6 cm (21.5 inch) with VA Panel Technology 1920 X 1080 Resolution Refresh Rate 75Hz Black Monitor",
              "imageUrl": "/medias/Acer-EK220Q-LED-492574200-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxNDg3MXxpbWFnZS9qcGVnfGltYWdlcy9oYzUvaDVjLzk4MzI4NTk5MjY1NTguanBnfDZlMDYwN2JlN2FkYzI1OGY5OWU2MzNlZWJiMDg2MWI4NTVkYzU0NzdhMzQ5YWU3YzA3NzMyOTlkODIyZjY0ZWU",
              "altText": "Acer EK220Q 54.6 cm (21.5 inch) with VA Panel Technology 1920 X 1080 Resolution Refresh Rate 75Hz Black Monitor",
              "url": "/acer-ek220q-54-6-cm-21-5-inch-with-va-panel-technology-1920-x-1080-resolution-refresh-rate-75hz-black-monitor/p/492574200",
              "mrp": "13750",
              "sellingPrice": "5399",
              "discount": "61%(₹8,351)",
              "deal": true,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>54.6 cm (21.5 inch) Full HD Resolution</li>\n<li>Connectivity Options: HDMI and VGA Ports</li>\n<li>Eye Care Feature</li>\n<li>Panel Technology: VA</li>",
              "skuId": "492574200",
              "masterCategory": {
                "code": "S101215",
                "name": "Computer Monitors",
                "url": "/computer-monitors/c/S101215",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "EK220Q",
              "numberOfReviews": 1,
              "numberOfRatings": 2,
              "averageRating": 5.0,
              "fullReviewUrl": null
            },
            {
              "name": "ZEBRONICS MT61-ZEB A22FHD 54.6 cm (21.5 inch), 1920 x 1080 Resolution, Black Monitor",
              "imageUrl": "/medias/ZEBRONICS-MT61-Monitor-492849914-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wzNTI2N3xpbWFnZS9qcGVnfGltYWdlcy9oNmIvaDU1Lzk4MTI4NzcxMTU0MjIuanBnfDNjYWZmNDg5OTFjNWI1YzZjYmZjZDkyODQzMzAyYzVhYTY5NjdlZWI1YjNlMWYwMzE1YTU4ZDdkYTI2ZGZlMTc",
              "altText": "ZEBRONICS MT61-ZEB A22FHD 54.6 cm (21.5 inch), 1920 x 1080 Resolution, Black Monitor",
              "url": "/zebronics-mt61-zeb-a22fhd-54-6-cm-21-5-inch-1920-x-1080-resolution-black-monitor/p/492849914",
              "mrp": "21999",
              "sellingPrice": "4999",
              "discount": "77%(₹17,000)",
              "deal": true,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>54.6 cm (21.5 inch) wide screen</li>\n<li>Slim design</li>\n<li>Connectivity: HDMI and VGA</li>\n<li>FHD1920 x 1080</li>\n<li>Built-in power supply</li>\n<li>Built-in speakers</li>\n<li>High glossy stand</li>\n<li>Wall mountable</li>",
              "skuId": "492849914",
              "masterCategory": {
                "code": "S101215",
                "name": "Computer Monitors",
                "url": "/computer-monitors/c/S101215",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "MT61-ZEB A22FHD",
              "numberOfReviews": 3,
              "numberOfRatings": 6,
              "averageRating": 4.5,
              "fullReviewUrl": null
            },
            {
              "name": "BenQ GW2780 68.58 cm (27 inch) IPS, Full HD, Built-in Speakers, HDMI, Display Port, Flicker-free Technology (Black), Monitor",
              "imageUrl": "/medias/Benq-GW2780-Monitor-492850948-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyNTA4OXxpbWFnZS9qcGVnfGltYWdlcy9oYWYvaDlhLzk4NjMyNTgxMTIwMzAuanBnfDU1M2Q5OTAwNDU5NjViMjc0ZWZjNjNjZmMyNDVkM2M4NTNjNmMxMmJkNzhjOTc1OGEzMmMwOWZhZjBhZTM1ZWU",
              "altText": "BenQ GW2780 68.58 cm (27 inch) IPS, Full HD, Built-in Speakers, HDMI, Display Port, Flicker-free Technology (Black), Monitor",
              "url": "/benq-gw2780-68-58-cm-27-inch-ips-full-hd-built-in-speakers-hdmi-display-port-flicker-free-technology-black-monitor/p/492850948",
              "mrp": "19990",
              "sellingPrice": "11399",
              "discount": "43%(₹8,591)",
              "deal": true,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>68.58 cm(27 inch) Eye-care IPS FHD Monitor</li>\n<li>1920x1080-Full HD Resolution</li>\n<li>Aspect Ratio: 16:9</li>\n<li>Edge to Edge Slim Bezel Design</li>\n<li>Equipped with Brightness Intelligence Technology</li>\n<li>Display Colors: 16.7 million color</li>",
              "skuId": "492850948",
              "masterCategory": {
                "code": "S101215",
                "name": "Computer Monitors",
                "url": "/computer-monitors/c/S101215",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "GW2780",
              "numberOfReviews": 0,
              "numberOfRatings": 0,
              "averageRating": 0.0,
              "fullReviewUrl": null
            },
            {
              "name": "ENTER A06 39.1 cm (15.4 inch) 1280 x 800 Resolution , Black Monitor",
              "imageUrl": "/medias/ENTER-A06-Computer-Monitor-492850691-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w3Mzc0OHxpbWFnZS9qcGVnfGltYWdlcy9oYWMvaGMxLzk4NTIyMzkwODU1OTguanBnfDQxMmM2ZDdiMjAxYjU1YWVjM2U1NTFlYjQ0ODM1NGFkMjg5NjI4NTJhNjNhMTQzYjM4ZGI0MzdlMzU1ODdkNDI",
              "altText": "ENTER A06 39.1 cm (15.4 inch) 1280 x 800 Resolution , Black Monitor",
              "url": "/enter-a06-39-1-cm-15-4-inch-1280-x-800-resolution-black-monitor/p/492850691",
              "mrp": "6000",
              "sellingPrice": "3299",
              "discount": "45%(₹2,701)",
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>39.1 cm (15.4 inch) LED Display</li>\n<li>Response Time: 5 ms (TD)</li>\n<li>Interface: VGA, HDMI</li>\n<li>Display Mode: VGA, SVGA, SXGA,WXGA</li>\n<li>Front Control: Power on/off with LED, OSD Menu, +/- adjustment auto</li>",
              "skuId": "492850691",
              "masterCategory": {
                "code": "S101215",
                "name": "Computer Monitors",
                "url": "/computer-monitors/c/S101215",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "A06",
              "numberOfReviews": 4,
              "numberOfRatings": 5,
              "averageRating": 4.0,
              "fullReviewUrl": null
            },
            {
              "name": "Acer EK240YC 60.5 cm (23.8 inch) with VA Panel Technology 1920 x 1080 Resolution Refresh Rate 75 Hz Black Monitor",
              "imageUrl": "/medias/Acer-EK240YC-LED-492574202-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxMjgxN3xpbWFnZS9qcGVnfGltYWdlcy9oOGIvaDY5Lzk4MzI4NTkyNzExOTguanBnfDJjNjJmOTgyMDdmNDZiNDljZDk4ZTgzYjA3MjU3ZGNiOGFhOWVlNGI2MmE1MWNkYTE2ZWIxY2NmMTYyYzIwN2Q",
              "altText": "Acer EK240YC 60.5 cm (23.8 inch) with VA Panel Technology 1920 x 1080 Resolution Refresh Rate 75 Hz Black Monitor",
              "url": "/acer-ek240yc-60-5-cm-23-8-inch-with-va-panel-technology-1920-x-1080-resolution-refresh-rate-75-hz-black-monitor/p/492574202",
              "mrp": "17500",
              "sellingPrice": "6399",
              "discount": "63%(₹11,101)",
              "deal": true,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>60.45 cm (23.8 Inch) VA Panel Full HD Resolution</li>\n<li>Connectivity Options : HDMI and VGA Ports</li>\n<li>Eye Care Feature</li>\n<li>Panel Technology: VA</li>",
              "skuId": "492574202",
              "masterCategory": {
                "code": "S101215",
                "name": "Computer Monitors",
                "url": "/computer-monitors/c/S101215",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "EK240YC",
              "numberOfReviews": 3,
              "numberOfRatings": 7,
              "averageRating": 4.9,
              "fullReviewUrl": null
            },
            {
              "name": "Dell D2020H. 49.53 cm (19.5-inch) 1600 x 900 Resolution, Black Monitor",
              "imageUrl": "/medias/Dell-D2020H-Monitors-491946999-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyNjY2NnxpbWFnZS9qcGVnfGltYWdlcy9oODYvaGY2Lzk3NzI3OTY4NzA2ODYuanBnfGExMWVlZjYyMGMzYWY1MDRiYjM4ZDM2NGJmZWQzYmQyYWUyMDg5ZDY4MTdiNjhiYzFhYjhiZTA1MjQ1NzVkYjQ",
              "altText": "Dell D2020H. 49.53 cm (19.5-inch) 1600 x 900 Resolution, Black Monitor",
              "url": "/dell-d2020h-49-53-cm-19-5-inch-1600-x-900-resolution-black-monitor/p/491946999",
              "mrp": "12529",
              "sellingPrice": "6199",
              "discount": "51%(₹6,330)",
              "deal": true,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>49.53 cm (19.5-inch) HD Anti Glare Display</li>\n<li>Adjustable Stand</li>\n<li>Viewing Angle: 90 Degree / 50 Degree</li>\n<li>Flicker Free Technolgy</li>",
              "skuId": "491946999",
              "masterCategory": {
                "code": "S101215",
                "name": "Computer Monitors",
                "url": "/computer-monitors/c/S101215",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "D2020H.",
              "numberOfReviews": 0,
              "numberOfRatings": 0,
              "averageRating": 0.0,
              "fullReviewUrl": null
            },
            {
              "name": "Samsung LS32BM500EWXXL 81.3 cm (32 inch) VA Panel, 1920 X 1080 Resolution, Built-in Speaker, HDMI, Flicker Free, Black, Monitor",
              "imageUrl": "/medias/Samsung-LS32BM500EWXXL-computer-monitor-493178931-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w1MzUwNHxpbWFnZS9qcGVnfGltYWdlcy9oMzUvaDQ3Lzk5MjIwNjk2MjY5MTAuanBnfDIyNjhmNmM1NmU2ZDFkODJjODQ3OWNjMTUzNDRmNzZkMjczMWMwYTZmYzdhYTAyZTMyMzVhZmQ1NWQwNzdiMTM",
              "altText": "Samsung LS32BM500EWXXL 81.3 cm (32 inch) VA Panel, 1920 X 1080 Resolution, Built-in Speaker, HDMI, Flicker Free, Black, Monitor",
              "url": "/samsung-ls32bm500ewxxl-81-3-cm-32-inch-va-panel-1920-x-1080-resolution-built-in-speaker-hdmi-flicker-free-black-monitor/p/493178931",
              "mrp": "21500",
              "sellingPrice": "20199",
              "discount": "6%(₹1,301)",
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Tizen Operating System, SlimFit camera</li>\n<li>Watch, work and chat - all without connecting a separate PC</li>\n<li>Smart TV experience with its embedded TV apps</li>\n<li>Samsung DeX, Office 365, Google Duo app and IoT Hub</li>\n<li>Convenient connectivity with Airplay and Auto Source Switch+</li>",
              "skuId": "493178931",
              "masterCategory": {
                "code": "S101215",
                "name": "Computer Monitors",
                "url": "/computer-monitors/c/S101215",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "LS32BM500EWXXL",
              "numberOfReviews": 0,
              "numberOfRatings": 0,
              "averageRating": 0.0,
              "fullReviewUrl": null
            },
            {
              "name": "LG 19M38AB 46.99 cm (18.5 Inch) TN Panel 1366 x 768 Black Monitor",
              "imageUrl": "/medias/Lg-19M38AB-Monitor-493178501-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wzMTA5MnxpbWFnZS9qcGVnfGltYWdlcy9oOGQvaDZhLzk5MTAxODAxNTEzMjYuanBnfGJkYjUwYjFiNTljZjY5ZTIwMDEyZmU3NzlkYTI0ZGJkNDQ1NTZmYzdhOGQwNGRkOGJiNGE1YzAxMWQyNzg2Zjc",
              "altText": "LG 19M38AB 46.99 cm (18.5 Inch) TN Panel 1366 x 768 Black Monitor",
              "url": "/lg-19m38ab-46-99-cm-18-5-inch-tn-panel-1366-x-768-black-monitor/p/493178501",
              "mrp": "8600",
              "sellingPrice": "5539",
              "discount": "36%(₹3,061)",
              "deal": true,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Size: 46.99 cm (18.5 Inch)</li>\n<li>Resolution: 1366 x 768</li>\n<li>Aspect Ratio: 16:9</li>\n<li>Display Type: LED</li>\n<li>Ports: VGA</li>",
              "skuId": "493178501",
              "masterCategory": {
                "code": "S101215",
                "name": "Computer Monitors",
                "url": "/computer-monitors/c/S101215",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "19M38AB",
              "numberOfReviews": 0,
              "numberOfRatings": 0,
              "averageRating": 0.0,
              "fullReviewUrl": null
            },
            {
              "name": "ZEBRONICS MT52-ZEB A19HD 46.9 cm (18.5 inch), 1366 x 768 Resolution, Black Monitor",
              "imageUrl": "/medias/Zebronics-MT52-ZEB-A19HD-LED-492849912-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxMzQ2N3xpbWFnZS9qcGVnfGltYWdlcy9oMTcvaDBiLzk4Mjk4MDMyOTQ3NTAuanBnfDIwMjRlNzkwM2EzMDY4MmJhNjUzYTFmOGY4YzBiNjg3OTIyZWQ5ZWE0MzU3NGZhYWNiYjE5MDU2NDM5Njc4MjA",
              "altText": "ZEBRONICS MT52-ZEB A19HD 46.9 cm (18.5 inch), 1366 x 768 Resolution, Black Monitor",
              "url": "/zebronics-mt52-zeb-a19hd-46-9-cm-18-5-inch-1366-x-768-resolution-black-monitor/p/492849912",
              "mrp": "9999",
              "sellingPrice": "4999",
              "discount": "50%(₹5,000)",
              "deal": true,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Slim and glossy Design</li>\n<li>Anti glare</li>\n<li>Wall Mountable</li>\n<li>HD 1366 x 768</li>\n<li>Built-in power supply</li>\n<li>HDMI and VGA input</li>",
              "skuId": "492849912",
              "masterCategory": {
                "code": "S101215",
                "name": "Computer Monitors",
                "url": "/computer-monitors/c/S101215",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "MT52-ZEB A19HD",
              "numberOfReviews": 1,
              "numberOfRatings": 1,
              "averageRating": 4.0,
              "fullReviewUrl": null
            },
            {
              "name": "Acer HA220Q 54.61 cm (21.5 inch) with IPS Panel Technology 1920 x 1080 Resolution 2W Speakers White Monitor",
              "imageUrl": "/medias/Acer-HA220Q-Monitors-492849987-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w4ODc1NHxpbWFnZS9qcGVnfGltYWdlcy9oMjYvaDUyLzk4MTczMDMzODQwOTQuanBnfDRiMzY1YjAwNmUxNzUxMjFkYzcwOTA3ZTRlMmY0ZjliMjI2NGExMmQzNmUyYTE3NmNhMWZhODI1NmU1MDhiZDQ",
              "altText": "Acer HA220Q 54.61 cm (21.5 inch) with IPS Panel Technology 1920 x 1080 Resolution 2W Speakers White Monitor",
              "url": "/acer-ha220q-54-61-cm-21-5-inch-with-ips-panel-technology-1920-x-1080-resolution-2w-speakers-white-monitor/p/492849987",
              "mrp": "15700",
              "sellingPrice": "11499",
              "discount": "27%(₹4,201)",
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>54.61 cm (21.5 inch) FHD IPS Ultra Thin Monitor</li><li>Ultra Slim (6.6mm Thick)</li><li>Ports: 1 VGA Port, 1 HDMI, 1 Audio-In</li><li>250 Nits Brightness, 75Hz, 4ms</li><li>2W X 2 Stereo Speakers</li><li>Frameless Design, AMDFree Sync  and more in the",
              "skuId": "492849987",
              "masterCategory": {
                "code": "S101215",
                "name": "Computer Monitors",
                "url": "/computer-monitors/c/S101215",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "HA220Q",
              "numberOfReviews": 1,
              "numberOfRatings": 2,
              "averageRating": 4.5,
              "fullReviewUrl": null
            }
          ]
        },
        {
          "componentType": "comp_0000PQP4",
          "visible": true,
          "name": "Best Selling Audio Accessories",
          "isDealTimerComponent": false,
          "dealTimerDetails": null,
          "displayName": "Best Selling Audio Accessories",
          "viewAllUrl": "https://www.reliancedigital.in/page/festival-of-electronics-2023-top-selling-products-True-wireless?internal_source=HP&internal_medium=Product-Carousel&internal_campaign=Best-Selling-Audio-Accessories",
          "bannerPosition": null,
          "banners": [
            
          ],
          "data": [
            {
              "name": "Sony XB910N Wireless Bluetooth Headphone with Extra Bass, Upto 30 hrs of playtime, Multipoint connection, Voice assistant,  Noise cancellation, Extra Bass sound, Built-In Alexa , Blue",
              "imageUrl": "/medias/Sony-XB910N-Headphones-492796749-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w1Mzc0MnxpbWFnZS9qcGVnfGltYWdlcy9oODMvaGI2Lzk4MDkxMjMxNDc4MDYuanBnfDhkZjczNjdhOGUwZGI1ODkwMDY5OGRiNDFlMDQ3YTUyMDZiMzA1Njg5ZjUzNmUyNWViN2JlYjk4MWRmYjhiZTU",
              "altText": "Sony XB910N Wireless Bluetooth Headphone with Extra Bass, Upto 30 hrs of playtime, Multipoint connection, Voice assistant,  Noise cancellation, Extra Bass sound, Built-In Alexa , Blue",
              "url": "/sony-xb910n-wireless-bluetooth-headphone-with-extra-bass-upto-30-hrs-of-playtime-multipoint-connection-voice-assistant-noise-cancellation-extra-bass-sound-built-in-alexa-blue/p/492796749",
              "mrp": "19990",
              "sellingPrice": "8999",
              "discount": "55%(₹10,991)",
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": "Upto 12 months No cost EMI",
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Noise cancelling: Active Noise Cancellation (ANC) lends a personalized, virtually soundproof experience at any situation</li><li>Voice assistant: Alexa, Google Assistant & Siri enabled (In-built) for voice access to music, information and more. Activate with a simple touch</li><li>Quick attention mode: Cover the right ear cup with your palm to turn down music for instant, easy conversation</li><li>Smart listening: WH-XB910N adjusts the ambient sound to your activity to give you the best noise cancellation</li><li>Long battery life/Quick Charge: A single charge provides up to 30 hrs of playtime for reliable all day listening and Quick charge for 10min charge for 4.5 hours play back</li><li>Multipoint connection : It can be paired with two Bluetooth devices at the same time. So when a call comes in, your headphones know which device is ringing and connect to the right one automatically.</li><li>Touch controls: Change the track, turn the volume up or down and take or make calls by tapping or swiping the panel with your fingertip</li><li>Google Fast Pair : Fast Pair makes it easy to pair your headphones with your Android devices</li><li>Swift Pair : Swift Pair makes it quick and easy to pair your WH-XB910N headphones with your Windows 10 computer via Bluetooth</li>",
              "skuId": "492796749",
              "masterCategory": {
                "code": "S101021",
                "name": "Headphones & Headsets",
                "url": "/headphones-headsets/c/S101021",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "WH-XB910N/LZIN",
              "numberOfReviews": 0,
              "numberOfRatings": 1,
              "averageRating": 5.0,
              "fullReviewUrl": null
            },
            {
              "name": "Apple Airpods Pro (2nd Gen-USB-C type) with MagSafe Charging Case True Wireless, with Active Noise Cancellation, Touch control, IP54 Dust, Sweat and water resistant, Bluetooth v5.3, Upto 30 hrs of playtime, White",
              "imageUrl": "/medias/Apple-Airpods-Pro-2nd-Gen-493839243-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyMDE0N3xpbWFnZS9qcGVnfGltYWdlcy9oNjcvaDI5LzEwMDUwNzMxNDA5NDM4LmpwZ3w1MGE2NjQxZWU0M2Y5ZmNkY2Y3YzYwNmMzNzc2YTRmZmQ3NDhhZGQ3MzY4MDU5NzhjYTdhMzhlODM1Zjk4NTQw",
              "altText": "Apple Airpods Pro (2nd Gen-USB-C type) with MagSafe Charging Case True Wireless, with Active Noise Cancellation, Touch control, IP54 Dust, Sweat and water resistant, Bluetooth v5.3, Upto 30 hrs of playtime, White",
              "url": "/apple-airpods-pro-2nd-gen-usb-c-type-with-magsafe-charging-case-true-wireless-with-active-noise-cancellation-touch-control-ip54-dust-sweat-and-water-resistant-bluetooth-v5-3-upto-30-hrs-of-playtime-white/p/493839243",
              "mrp": "24900",
              "sellingPrice": "22990",
              "discount": "8%(₹1,910)",
              "deal": true,
              "inStock": true,
              "hasPP": true,
              "teaserType": "Rs.2000 Instant Discount on ICICI & SBI Bank Cards*",
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Adaptive Audio</li>\n<li>H2 Apple silicon, amazing sound quality with Adaptive EQ</li>\n<li>Active Noise Cancellation and Transparency Mode</li>\n<li>IP54 Dust-Sweat and Water Resistant AirPods and Charging Case</li>\n<li>MagSafe Charging Case (USB‑C) with Speaker and Lanyard Loop</li>\n<li>Up to 6 hours of listening time with a single charge</li>",
              "skuId": "493839243",
              "masterCategory": {
                "code": "S10102110",
                "name": "True Wireless",
                "url": "/true-wireless/c/S10102110",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "MTJV3HN/A",
              "numberOfReviews": 5,
              "numberOfRatings": 20,
              "averageRating": 4.9,
              "fullReviewUrl": null
            },
            {
              "name": "boAt Nirvana Ion ANC True Wireless Earbuds with Upto 120 Hours of Total Playback, Beast Mode, Dual EQ Modes, ANC with ENx Technology, Bluetooth v5.2, Crystal Black",
              "imageUrl": "/medias/boAt-Nirvana-Ion-Earbud-494249958-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w1Mjk2NHxpbWFnZS9qcGVnfGltYWdlcy9oNmMvaGQ5LzEwMDkyNTIyNjM1Mjk0LmpwZ3xiZmE4NmE5ZjZkZTYzYjM1ZTc3ZmUyMGFmMzQyZTNhNGE2Yjg0NzY2NzQxMjYwYzUwMjgyZmJlNGJmMDdiYmQ0",
              "altText": "boAt Nirvana Ion ANC True Wireless Earbuds with Upto 120 Hours of Total Playback, Beast Mode, Dual EQ Modes, ANC with ENx Technology, Bluetooth v5.2, Crystal Black",
              "url": "/boat-nirvana-ion-anc-true-wireless-earbuds-with-upto-120-hours-of-total-playback-beast-mode-dual-eq-modes-anc-with-enx-technology-bluetooth-v5-2-crystal-black/p/494249958",
              "mrp": "9990",
              "sellingPrice": "1999",
              "discount": "80%(₹7,991)",
              "deal": true,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>24 Hours Earbuds Playback & 120 Hours Total Playback</li>\n<li>Crystal Bionic Sound Powered by HiFi</li>\n<li>Active Noise Cancellation Up To 32dB</li>\n<li>Mics ENx Technology</li>\n<li>Low Latency = Synced Entertainment</li>\n<li>Dual EQ Modes: Bass & Balanced</li>",
              "skuId": "494249958",
              "masterCategory": {
                "code": "S10102110",
                "name": "True Wireless",
                "url": "/true-wireless/c/S10102110",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "Nirvana Ion ANC",
              "numberOfReviews": 17,
              "numberOfRatings": 17,
              "averageRating": 4.9,
              "fullReviewUrl": null
            },
            {
              "name": "Apple EarPods with Lightning Connector, Protection from sweat and water, Built-in Remote and Mic",
              "imageUrl": "/medias/Apple-Wired-EarPods-with-Lightning-Connector-White-491277319-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxMzUyMnxpbWFnZS9qcGVnfGltYWdlcy9oMmQvaDcwLzg5MzI3MTk3MjI1MjYuanBnfDk3MmQ1OWQyNTk2MjJmYjQyOWY0MGJkYzYyM2M0MGVhZTFlMjVhZjU5ZjVhODNkYzgxMWJkMGQzZTdhNTdmZjY",
              "altText": "Apple EarPods with Lightning Connector, Protection from sweat and water, Built-in Remote and Mic",
              "url": "/apple-earpods-with-lightning-connector-protection-from-sweat-and-water-built-in-remote-and-mic/p/491277319",
              "mrp": "2000",
              "sellingPrice": "1599",
              "discount": "20%(₹401)",
              "deal": true,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Built-in Remote & Mic - Control Music & Answer or End Calls</li>\n<li>Protection from Sweat & Water</li>",
              "skuId": "491277319",
              "masterCategory": {
                "code": "S10102113",
                "name": "Wired Earphones",
                "url": "/wired-earphones/c/S10102113",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "MMTN2ZM/A",
              "numberOfReviews": 84,
              "numberOfRatings": 441,
              "averageRating": 4.8,
              "fullReviewUrl": null
            },
            {
              "name": "Sony WF-1000XM4 True Wireless Earbuds with Noise Cancellation, 8 hrs of playtime, Integrated Processor V1, IPX4 Water Resistance, Speak-to-chat Technology, Qi technology, Black",
              "imageUrl": "/medias/Sony-WF-1000XM4-Headphones-and-Headsets-492579491-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wzMDE4N3xpbWFnZS9qcGVnfGltYWdlcy9oOTYvaGUyLzk3NTU3MDQ2NTU5MDIuanBnfGQyMDMyYjEwYTBhOGMyY2I1YzJkNzM3MjQ2MDIwMTE2MjY4OWU1YTNkZGM0ZjRkNjRmOGIxYmE2YTcyNjNlNWE",
              "altText": "Sony WF-1000XM4 True Wireless Earbuds with Noise Cancellation, 8 hrs of playtime, Integrated Processor V1, IPX4 Water Resistance, Speak-to-chat Technology, Qi technology, Black",
              "url": "/sony-wf-1000xm4-true-wireless-earbuds-with-noise-cancellation-8-hrs-of-playtime-integrated-processor-v1-ipx4-water-resistance-speak-to-chat-technology-qi-technology-black/p/492579491",
              "mrp": "19990",
              "sellingPrice": "9999",
              "discount": "50%(₹9,991)",
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": "Upto 6 months No cost EMI",
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Integrated Processor V1</li>\n<li>Supporting LDAC Codec</li>\n<li>Crystal-clear Call Quality</li>\n<li>Speak-to-chat Technology</li>\n<li>8 hours long battery with Noise Cancellation</li>\n<li>IPX4 Water Resistance</li>",
              "skuId": "492579491",
              "masterCategory": {
                "code": "S10102110",
                "name": "True Wireless",
                "url": "/true-wireless/c/S10102110",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "WF-1000XM4/Black",
              "numberOfReviews": 2,
              "numberOfRatings": 6,
              "averageRating": 4.3,
              "fullReviewUrl": null
            },
            {
              "name": "boAt Rockerz 410 Bluetooth Headphone with Mic, Super Extra Bass, Up to 8H Playtime, Dual Connectivity Modes, Foldable Ear cups and Lightweight Design, Red",
              "imageUrl": "/medias/Boat-Rockerz-410-Headphone-491598556-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxNzgzOXxpbWFnZS9qcGVnfGltYWdlcy9oNzgvaGFkLzk3NjU0MDUyNjE4NTQuanBnfDZlMDk0Njg4NTg1Nzc2MDgwMzgzZTc5ODg2MzI5MWVkNTk0ODAzZWM3MTRkMDlhZDhlM2FjMjRkMTU0ZjYxMDU",
              "altText": "boAt Rockerz 410 Bluetooth Headphone with Mic, Super Extra Bass, Up to 8H Playtime, Dual Connectivity Modes, Foldable Ear cups and Lightweight Design, Red",
              "url": "/boat-rockerz-410-bluetooth-headphone-with-mic-super-extra-bass-up-to-8h-playtime-dual-connectivity-modes-foldable-ear-cups-and-lightweight-design-red/p/491598556",
              "mrp": "2990",
              "sellingPrice": "999",
              "discount": "67%(₹1,991)",
              "deal": true,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Nonstop music upto 8 hours</li>\n<li>Work from home pro headset</li>\n<li>Extra Bass, Lightweight & Portable design</li>\n<li>40 mm dynamic drivers, 300 mAh battery</li>\n<li>Activate voice assistant with one-click</li>\n<li>Bluetooth v5.0 Connectivity, 10 m Bluetooth range</li>",
              "skuId": "491598556",
              "masterCategory": {
                "code": "S10102114",
                "name": "Bluetooth Headphones",
                "url": "/bluetooth-headphones/c/S10102114",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "ROCKERZ 410",
              "numberOfReviews": 0,
              "numberOfRatings": 0,
              "averageRating": 0.0,
              "fullReviewUrl": null
            },
            {
              "name": "OnePlus Bullets Z2 Bluetooth Wireless in Ear Earphones with Mic, Bombastic Bass, 10 Mins Charge - 20 Hrs Music, 30 Hrs Battery Life (Acoustic Red)",
              "imageUrl": "/medias/OnePlus-Bullets-Z2-Earphone-492913029-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w5OTc4fGltYWdlL2pwZWd8aW1hZ2VzL2g0OS9oZjcvOTg1NzY4OTYxNjQxNC5qcGd8NjdkMjhiODI0MDVlOTU2ZDNlYmM2YjY4ZTUxMWRhYmE0YzMyZmZkMzUwYWNiNDBhYjBmOWIzMGU1NWUwMWMyMw",
              "altText": "OnePlus Bullets Z2 Bluetooth Wireless in Ear Earphones with Mic, Bombastic Bass, 10 Mins Charge - 20 Hrs Music, 30 Hrs Battery Life (Acoustic Red)",
              "url": "/oneplus-bullets-z2-bluetooth-wireless-in-ear-earphones-with-mic-bombastic-bass-10-mins-charge---20-hrs-music-30-hrs-battery-life-acoustic-red-/p/492913029",
              "mrp": "2299",
              "sellingPrice": "1799",
              "discount": "22%(₹500)",
              "deal": false,
              "inStock": true,
              "hasPP": true,
              "teaserType": "Rs.150 Instant discount on ICICI",
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>A quick 10-minute charge delivers up to 20 hours of immersive audio playback. Frequency Response Range 20Hz - 20,000KHz. Bluetooth Connection range Up to 10 meters; The flagship-level battery life delivers up to 30 hours of non-stop music on a single charge. Codec: Supports AAC and SBC</li><li>A large 12.4 mm bass driver delivers uncompromisingly deep bass for powerful beats. Experience incredibly rich audio detail at every frequency with the titanium coating dome</li><li>Anti-distortion audio technology ensures your audio playtime stays silky-smooth. Thanks to the larger sound cavity and industry-leading algorithms, notes remain distortion-free</li><li>Water and sweat-resistant, the IP55-rated internals and design ensure your OnePlus Bullets Wireless Z2 stay all-weather ready.</li><li>Battery Average Life: 30.0Hours; Model: E305a; Frequency Range: 20hz - 20khz; Control Type: Call Control</li>",
              "skuId": "492913029",
              "masterCategory": {
                "code": "S10102111",
                "name": "Bluetooth Neckbands",
                "url": "/bluetooth-neckbands/c/S10102111",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "E305A",
              "numberOfReviews": 23,
              "numberOfRatings": 184,
              "averageRating": 4.7,
              "fullReviewUrl": null
            },
            {
              "name": "Amazon Echo Dot (3rd Gen) New and Improved Smart Speaker with Alexa, 360 degree Sound, Black",
              "imageUrl": "/medias/Amazon-Echo-dot-3-0-BK-Computer-Speaker-491431035-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w2NDM4fGltYWdlL2pwZWd8aW1hZ2VzL2hjZC9oMDcvOTA1OTQ0NzI0Mjc4Mi5qcGd8NmY3NDc0YjVjZjQ2ZmYyNmQ2MTA5NjhhZWFhYzQ5YzQ3YzE5Yzc1NjZhMGE1OWQ4NjhmN2U2YWUyODc5NDA4NQ",
              "altText": "Amazon Echo Dot (3rd Gen) New and Improved Smart Speaker with Alexa, 360 degree Sound, Black",
              "url": "/amazon-echo-dot-3rd-gen-new-and-improved-smart-speaker-with-alexa-360-degree-sound-black/p/491431035",
              "mrp": "3499",
              "sellingPrice": "3499",
              "discount": null,
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>3rd Generation Echo Dot-Smart Speaker with Alexa that can be operated by voice. Alexa can speak English and Hindi.</li> <li>Just ask Alexa to play music from Amazon Music, Hungama, Spotify, Jio Saavn, Apple Music. (some apps may require subscription).</li> <li>Voice control Alexa compatible smart appliances like lights, ACs, TVs, geysers. Extend the experience to non-smart appliances using smart plugs (to be purchased separately)</li> <li>Manage your day better by just asking Alexa to set reminders, pay bills, read news and much more.</li> <li>Use as a standalone speaker or pair your phone to use it as a Bluetooth speaker</li> <li>Echo Dot comes with multiple privacy controls, including a mic off button.</li>",
              "skuId": "491431035",
              "masterCategory": {
                "code": "S101015",
                "name": "Bluetooth & WiFi Speakers",
                "url": "/bluetooth-wifi-speakers/c/S101015",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": null,
              "numberOfReviews": 6,
              "numberOfRatings": 79,
              "averageRating": 4.8,
              "fullReviewUrl": null
            },
            {
              "name": "Sony WH-CH720N Over-the-Ear Bluetooth Headphone with Active Noise Cancellation, Upto 35 hrs of playtime, Quick Charging, Bluetooth v5.2, Google, Alexa Voice Assistant, Black",
              "imageUrl": "/medias/Sony-WH-CH720N-Headphone-493711862-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wzMDYyNnxpbWFnZS9qcGVnfGltYWdlcy9oYmQvaGE0Lzk5ODE3NDI1MTQyMDYuanBnfGJmNGJjZmE2Mjk1Njk3ZjRmMzFlMWRmN2Y4MzM4YzZkYjg2NjE5YjQ2ODhkNDExODA4ZTAyMjgxZjIyMjViYzA",
              "altText": "Sony WH-CH720N Over-the-Ear Bluetooth Headphone with Active Noise Cancellation, Upto 35 hrs of playtime, Quick Charging, Bluetooth v5.2, Google, Alexa Voice Assistant, Black",
              "url": "/sony-wh-ch720n-over-the-ear-bluetooth-headphone-with-active-noise-cancellation-upto-35-hrs-of-playtime-quick-charging-bluetooth-v5-2-google-alexa-voice-assistant-black/p/493711862",
              "mrp": "16990",
              "sellingPrice": "7990",
              "discount": "53%(₹9,000)",
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": "Upto 6 months No cost EMI",
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Sony's lightest Wireless Noise-cancelling headband ever;Up to 50-hour battery life with quick charging (3 min charge for up to 1 hour of playback)</li><li>Multi-Point Connection helps to pair with two Bluetooth devices at the same time;Take noise cancelling to the next level with Sony s Integrated Processor V1,so you can fully immerse yourself in the music</li><li>Super comfortable and lightweight design ( 192 Grams );Adjustable Ambient Sound mode and Adaptive Sound control features tailors sound to suit the environment around you</li><li>High sound quality and well-balanced sound tuning; Crystal clear hands-free calling and voice assistant with Precise Voice Pickup technology</li><li>Control Type: Media Control</li>",
              "skuId": "493711862",
              "masterCategory": {
                "code": "S10102114",
                "name": "Bluetooth Headphones",
                "url": "/bluetooth-headphones/c/S10102114",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "WH-CH720N/BCIN",
              "numberOfReviews": 0,
              "numberOfRatings": 2,
              "averageRating": 5.0,
              "fullReviewUrl": null
            },
            {
              "name": "realme Buds T300 Truly Wireless in-Ear Earbuds with upto 40 hrs of playtime, IP55 Water & Dust resistance, 360 Spatial Audio Effect, 12.4 mm Dynamic Bass Driver, Supports Dolby Atmos, Stylish Black",
              "imageUrl": "/medias/Realme-Buds-Bluetooth-Headphones-494249530-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wzMDM3N3xpbWFnZS9qcGVnfGltYWdlcy9oZWIvaGMxLzEwMDQ5NjQ2MzYyNjU0LmpwZ3xiNTlhMTczYzJlOGE4YzBmMTgwZTNmMWNiNWFhZTE3ZjBjOWRlNTk1ZDUzYTVlMDJmMDI0OWFjYTBjMThkZWZk",
              "altText": "realme Buds T300 Truly Wireless in-Ear Earbuds with upto 40 hrs of playtime, IP55 Water & Dust resistance, 360 Spatial Audio Effect, 12.4 mm Dynamic Bass Driver, Supports Dolby Atmos, Stylish Black",
              "url": "/realme-buds-t300-truly-wireless-in-ear-earbuds-with-upto-40-hrs-of-playtime-ip55-water-dust-resistance-360-spatial-audio-effect-12-4-mm-dynamic-bass-driver-supports-dolby-atmos-stylish-black/p/494249530",
              "mrp": "3999",
              "sellingPrice": "2299",
              "discount": "43%(₹1,700)",
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": null,
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>12.4mm Dynamic Bass Driver;30dB Active Noise Cancellation</li><li>360 Spatial Audio Effect;Upto 40 Hours Total Playback with Fast-charging support of 10 min charging for 7 hours playback</li><li>50ms Ultra-low Latency; Supports Dolby Atmos</li><li>IP55 Dust and Water Resistance  Bluetooth v5.3  realme Link App Connectivity (only for Android)</li><li>Control Type: Voice Control</li>",
              "skuId": "494249530",
              "masterCategory": {
                "code": "S10102110",
                "name": "True Wireless",
                "url": "/true-wireless/c/S10102110",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "RMA2302",
              "numberOfReviews": 4,
              "numberOfRatings": 13,
              "averageRating": 4.8,
              "fullReviewUrl": null
            },
            {
                "name": "Sony XB910N Wireless Bluetooth Headphone with Extra Bass, Upto 30 hrs of playtime, Multipoint connection, Voice assistant,  Noise cancellation, Extra Bass sound, Built-In Alexa , Blue",
                "imageUrl": "/medias/Sony-XB910N-Headphones-492796749-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w1Mzc0MnxpbWFnZS9qcGVnfGltYWdlcy9oODMvaGI2Lzk4MDkxMjMxNDc4MDYuanBnfDhkZjczNjdhOGUwZGI1ODkwMDY5OGRiNDFlMDQ3YTUyMDZiMzA1Njg5ZjUzNmUyNWViN2JlYjk4MWRmYjhiZTU",
                "altText": "Sony XB910N Wireless Bluetooth Headphone with Extra Bass, Upto 30 hrs of playtime, Multipoint connection, Voice assistant,  Noise cancellation, Extra Bass sound, Built-In Alexa , Blue",
                "url": "/sony-xb910n-wireless-bluetooth-headphone-with-extra-bass-upto-30-hrs-of-playtime-multipoint-connection-voice-assistant-noise-cancellation-extra-bass-sound-built-in-alexa-blue/p/492796749",
                "mrp": "19990",
                "sellingPrice": "8999",
                "discount": "55%(₹10,991)",
                "deal": false,
                "inStock": true,
                "hasPP": false,
                "teaserType": "Upto 12 months No cost EMI",
                "preOrderEnabled": false,
                "preOrderDetails": null,
                "summary": "<li>Noise cancelling: Active Noise Cancellation (ANC) lends a personalized, virtually soundproof experience at any situation</li><li>Voice assistant: Alexa, Google Assistant & Siri enabled (In-built) for voice access to music, information and more. Activate with a simple touch</li><li>Quick attention mode: Cover the right ear cup with your palm to turn down music for instant, easy conversation</li><li>Smart listening: WH-XB910N adjusts the ambient sound to your activity to give you the best noise cancellation</li><li>Long battery life/Quick Charge: A single charge provides up to 30 hrs of playtime for reliable all day listening and Quick charge for 10min charge for 4.5 hours play back</li><li>Multipoint connection : It can be paired with two Bluetooth devices at the same time. So when a call comes in, your headphones know which device is ringing and connect to the right one automatically.</li><li>Touch controls: Change the track, turn the volume up or down and take or make calls by tapping or swiping the panel with your fingertip</li><li>Google Fast Pair : Fast Pair makes it easy to pair your headphones with your Android devices</li><li>Swift Pair : Swift Pair makes it quick and easy to pair your WH-XB910N headphones with your Windows 10 computer via Bluetooth</li>",
                "skuId": "492796749",
                "masterCategory": {
                  "code": "S101021",
                  "name": "Headphones & Headsets",
                  "url": "/headphones-headsets/c/S101021",
                  "description": null,
                  "image": null,
                  "parentCategoryName": null,
                  "sequence": 0
                },
                "productModelName": "WH-XB910N/LZIN",
                "numberOfReviews": 0,
                "numberOfRatings": 1,
                "averageRating": 5.0,
                "fullReviewUrl": null
              },
              {
                "name": "Apple Airpods Pro (2nd Gen-USB-C type) with MagSafe Charging Case True Wireless, with Active Noise Cancellation, Touch control, IP54 Dust, Sweat and water resistant, Bluetooth v5.3, Upto 30 hrs of playtime, White",
                "imageUrl": "/medias/Apple-Airpods-Pro-2nd-Gen-493839243-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyMDE0N3xpbWFnZS9qcGVnfGltYWdlcy9oNjcvaDI5LzEwMDUwNzMxNDA5NDM4LmpwZ3w1MGE2NjQxZWU0M2Y5ZmNkY2Y3YzYwNmMzNzc2YTRmZmQ3NDhhZGQ3MzY4MDU5NzhjYTdhMzhlODM1Zjk4NTQw",
                "altText": "Apple Airpods Pro (2nd Gen-USB-C type) with MagSafe Charging Case True Wireless, with Active Noise Cancellation, Touch control, IP54 Dust, Sweat and water resistant, Bluetooth v5.3, Upto 30 hrs of playtime, White",
                "url": "/apple-airpods-pro-2nd-gen-usb-c-type-with-magsafe-charging-case-true-wireless-with-active-noise-cancellation-touch-control-ip54-dust-sweat-and-water-resistant-bluetooth-v5-3-upto-30-hrs-of-playtime-white/p/493839243",
                "mrp": "24900",
                "sellingPrice": "22990",
                "discount": "8%(₹1,910)",
                "deal": true,
                "inStock": true,
                "hasPP": true,
                "teaserType": "Rs.2000 Instant Discount on ICICI & SBI Bank Cards*",
                "preOrderEnabled": false,
                "preOrderDetails": null,
                "summary": "<li>Adaptive Audio</li>\n<li>H2 Apple silicon, amazing sound quality with Adaptive EQ</li>\n<li>Active Noise Cancellation and Transparency Mode</li>\n<li>IP54 Dust-Sweat and Water Resistant AirPods and Charging Case</li>\n<li>MagSafe Charging Case (USB‑C) with Speaker and Lanyard Loop</li>\n<li>Up to 6 hours of listening time with a single charge</li>",
                "skuId": "493839243",
                "masterCategory": {
                  "code": "S10102110",
                  "name": "True Wireless",
                  "url": "/true-wireless/c/S10102110",
                  "description": null,
                  "image": null,
                  "parentCategoryName": null,
                  "sequence": 0
                },
                "productModelName": "MTJV3HN/A",
                "numberOfReviews": 5,
                "numberOfRatings": 20,
                "averageRating": 4.9,
                "fullReviewUrl": null
              },
              {
                "name": "boAt Nirvana Ion ANC True Wireless Earbuds with Upto 120 Hours of Total Playback, Beast Mode, Dual EQ Modes, ANC with ENx Technology, Bluetooth v5.2, Crystal Black",
                "imageUrl": "/medias/boAt-Nirvana-Ion-Earbud-494249958-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w1Mjk2NHxpbWFnZS9qcGVnfGltYWdlcy9oNmMvaGQ5LzEwMDkyNTIyNjM1Mjk0LmpwZ3xiZmE4NmE5ZjZkZTYzYjM1ZTc3ZmUyMGFmMzQyZTNhNGE2Yjg0NzY2NzQxMjYwYzUwMjgyZmJlNGJmMDdiYmQ0",
                "altText": "boAt Nirvana Ion ANC True Wireless Earbuds with Upto 120 Hours of Total Playback, Beast Mode, Dual EQ Modes, ANC with ENx Technology, Bluetooth v5.2, Crystal Black",
                "url": "/boat-nirvana-ion-anc-true-wireless-earbuds-with-upto-120-hours-of-total-playback-beast-mode-dual-eq-modes-anc-with-enx-technology-bluetooth-v5-2-crystal-black/p/494249958",
                "mrp": "9990",
                "sellingPrice": "1999",
                "discount": "80%(₹7,991)",
                "deal": true,
                "inStock": true,
                "hasPP": false,
                "teaserType": null,
                "preOrderEnabled": false,
                "preOrderDetails": null,
                "summary": "<li>24 Hours Earbuds Playback & 120 Hours Total Playback</li>\n<li>Crystal Bionic Sound Powered by HiFi</li>\n<li>Active Noise Cancellation Up To 32dB</li>\n<li>Mics ENx Technology</li>\n<li>Low Latency = Synced Entertainment</li>\n<li>Dual EQ Modes: Bass & Balanced</li>",
                "skuId": "494249958",
                "masterCategory": {
                  "code": "S10102110",
                  "name": "True Wireless",
                  "url": "/true-wireless/c/S10102110",
                  "description": null,
                  "image": null,
                  "parentCategoryName": null,
                  "sequence": 0
                },
                "productModelName": "Nirvana Ion ANC",
                "numberOfReviews": 17,
                "numberOfRatings": 17,
                "averageRating": 4.9,
                "fullReviewUrl": null
              },
              {
                "name": "Apple EarPods with Lightning Connector, Protection from sweat and water, Built-in Remote and Mic",
                "imageUrl": "/medias/Apple-Wired-EarPods-with-Lightning-Connector-White-491277319-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxMzUyMnxpbWFnZS9qcGVnfGltYWdlcy9oMmQvaDcwLzg5MzI3MTk3MjI1MjYuanBnfDk3MmQ1OWQyNTk2MjJmYjQyOWY0MGJkYzYyM2M0MGVhZTFlMjVhZjU5ZjVhODNkYzgxMWJkMGQzZTdhNTdmZjY",
                "altText": "Apple EarPods with Lightning Connector, Protection from sweat and water, Built-in Remote and Mic",
                "url": "/apple-earpods-with-lightning-connector-protection-from-sweat-and-water-built-in-remote-and-mic/p/491277319",
                "mrp": "2000",
                "sellingPrice": "1599",
                "discount": "20%(₹401)",
                "deal": true,
                "inStock": true,
                "hasPP": false,
                "teaserType": null,
                "preOrderEnabled": false,
                "preOrderDetails": null,
                "summary": "<li>Built-in Remote & Mic - Control Music & Answer or End Calls</li>\n<li>Protection from Sweat & Water</li>",
                "skuId": "491277319",
                "masterCategory": {
                  "code": "S10102113",
                  "name": "Wired Earphones",
                  "url": "/wired-earphones/c/S10102113",
                  "description": null,
                  "image": null,
                  "parentCategoryName": null,
                  "sequence": 0
                },
                "productModelName": "MMTN2ZM/A",
                "numberOfReviews": 84,
                "numberOfRatings": 441,
                "averageRating": 4.8,
                "fullReviewUrl": null
              },
              {
                "name": "Sony WF-1000XM4 True Wireless Earbuds with Noise Cancellation, 8 hrs of playtime, Integrated Processor V1, IPX4 Water Resistance, Speak-to-chat Technology, Qi technology, Black",
                "imageUrl": "/medias/Sony-WF-1000XM4-Headphones-and-Headsets-492579491-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wzMDE4N3xpbWFnZS9qcGVnfGltYWdlcy9oOTYvaGUyLzk3NTU3MDQ2NTU5MDIuanBnfGQyMDMyYjEwYTBhOGMyY2I1YzJkNzM3MjQ2MDIwMTE2MjY4OWU1YTNkZGM0ZjRkNjRmOGIxYmE2YTcyNjNlNWE",
                "altText": "Sony WF-1000XM4 True Wireless Earbuds with Noise Cancellation, 8 hrs of playtime, Integrated Processor V1, IPX4 Water Resistance, Speak-to-chat Technology, Qi technology, Black",
                "url": "/sony-wf-1000xm4-true-wireless-earbuds-with-noise-cancellation-8-hrs-of-playtime-integrated-processor-v1-ipx4-water-resistance-speak-to-chat-technology-qi-technology-black/p/492579491",
                "mrp": "19990",
                "sellingPrice": "9999",
                "discount": "50%(₹9,991)",
                "deal": false,
                "inStock": true,
                "hasPP": false,
                "teaserType": "Upto 6 months No cost EMI",
                "preOrderEnabled": false,
                "preOrderDetails": null,
                "summary": "<li>Integrated Processor V1</li>\n<li>Supporting LDAC Codec</li>\n<li>Crystal-clear Call Quality</li>\n<li>Speak-to-chat Technology</li>\n<li>8 hours long battery with Noise Cancellation</li>\n<li>IPX4 Water Resistance</li>",
                "skuId": "492579491",
                "masterCategory": {
                  "code": "S10102110",
                  "name": "True Wireless",
                  "url": "/true-wireless/c/S10102110",
                  "description": null,
                  "image": null,
                  "parentCategoryName": null,
                  "sequence": 0
                },
                "productModelName": "WF-1000XM4/Black",
                "numberOfReviews": 2,
                "numberOfRatings": 6,
                "averageRating": 4.3,
                "fullReviewUrl": null
              },
          ]
        },
        {
          "componentType": "comp_0000SRI1",
          "visible": true,
          "name": "Limited Time Offers on Televisions",
          "isDealTimerComponent": false,
          "dealTimerDetails": null,
          "displayName": "Limited Time Offers on Televisions",
          "viewAllUrl": "https://www.reliancedigital.in/search?q=:relevance:productTags:limited-time-offers-televisions:availability:Exclude out of Stock&page=0&internal_source=HP&internal_medium=HPMC&internal_campaign=limited-time-offers-televisions",
          "bannerPosition": null,
          "banners": [
            
          ],
          "data": [
            {
              "name": "Samsung Crystal 4K Vivid 108 cm (43 inch) Ultra HD (4K) LED Smart Tizen TV  (UA43DUE70B )- 2024 Edition ",
              "imageUrl": "/medias/SAMSUNG-43DUE70B-LED-TVs-494410260-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w4NzgxM3xpbWFnZS9qcGVnfGltYWdlcy9oZjIvaDc2LzEwMTI5MzE5Mjk3MDU0LmpwZ3w4Y2Q5YmVjYzZmYzE5ZWY2OWNlZjRmN2RkNDg0OTcwNjY1MmU1ZjA4YTdhYmY4NWEzNWUzMTAxZTgyNmRlZjdl",
              "altText": "Samsung Crystal 4K Vivid 108 cm (43 inch) Ultra HD (4K) LED Smart Tizen TV  (UA43DUE70B )- 2024 Edition ",
              "url": "/samsung-crystal-4k-vivid-108-cm-43-inch-ultra-hd-4k-led-smart-tizen-tv-ua43due70b---2024-edition-/p/494410260",
              "mrp": "44900",
              "sellingPrice": "32990",
              "discount": "27%(₹11,910)",
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": "10_percent_Instant_Bank_Discount",
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Supported Apps: NetFlix, Prime Video, Samsung TV Plus, Disney + Hotstar</li>\n<li>Operating System: Tizen</li>\n<li>Resolution: 3840 x 2160 4K Ultra HD</li>\n<li>Connectivity: 3 HDMI and 1 USB Ports</li>\n<li>Sound Output (RMS): 20 Watt </li>\n<li>Refresh Rate: 50 Hz</li>",
              "skuId": "494410260",
              "masterCategory": {
                "code": "S101812",
                "name": "Televisions",
                "url": "/televisions/c/S101812",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "UA43DUE70BKLXL",
              "numberOfReviews": 0,
              "numberOfRatings": 0,
              "averageRating": 0.0,
              "fullReviewUrl": null
            },
            {
              "name": "Samsung Crystal 4K Vivid 138 cm (55 inch) Ultra HD (4K) LED Smart Tizen TV  (UA55DUE70B) - 2024 Edition ",
              "imageUrl": "/medias/SAMSUNG-55DUE70B-LED-TVs-494410248-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w4NzgxM3xpbWFnZS9qcGVnfGltYWdlcy9oOWUvaGQyLzEwMTI5MzI2ODMzNjk0LmpwZ3w0MDZkM2I1ZGViZTQ0NzczZDcwZGQxNTNlNDNiNTIxMTVjNTY4M2IwN2I2YzUwMjFkNmU5MmYwNTQwYTgyMDll",
              "altText": "Samsung Crystal 4K Vivid 138 cm (55 inch) Ultra HD (4K) LED Smart Tizen TV  (UA55DUE70B) - 2024 Edition ",
              "url": "/samsung-crystal-4k-vivid-138-cm-55-inch-ultra-hd-4k-led-smart-tizen-tv-ua55due70b---2024-edition-/p/494410248",
              "mrp": "64900",
              "sellingPrice": "46990",
              "discount": "28%(₹17,910)",
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": "10_percent_Instant_Bank_Discount",
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Supported Apps: NetFlix, Prime Video, Samsung TV Plus, Disney + Hotstar</li>\n<li>Operating System: Tizen</li>\n<li>Resolution: 3840 x 2160 4K Ultra HD</li>\n<li>Connectivity: 3 HDMI and 1 USB Ports</li>\n<li>Sound Output (RMS): 20 Watt </li>\n<li>Refresh Rate: 50 Hz</li>",
              "skuId": "494410248",
              "masterCategory": {
                "code": "S101812",
                "name": "Televisions",
                "url": "/televisions/c/S101812",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "UA55DUE70BKLXL",
              "numberOfReviews": 0,
              "numberOfRatings": 0,
              "averageRating": 0.0,
              "fullReviewUrl": null
            },
            {
              "name": "Samsung Crystal 4K Vivid 125 cm (50 inch) Ultra HD (4K) LED Smart Tizen TV (UA50DUE70B) - 2024 Edition",
              "imageUrl": "/medias/SAMSUNG-50DUE70-LED-TVs-494410254-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w4NzgxM3xpbWFnZS9qcGVnfGltYWdlcy9oNjkvaDYwLzEwMTM4ODMyMDExMjk0LmpwZ3w0MTc0MGZkMjRlMzMwNDg1NDQ4NjExMmUwNzUyMTY0MTkzYTNlYmFlZjMxMTY3YjUyMmExNzcyZTRiZWYzMmE2",
              "altText": "Samsung Crystal 4K Vivid 125 cm (50 inch) Ultra HD (4K) LED Smart Tizen TV (UA50DUE70B) - 2024 Edition",
              "url": "/samsung-crystal-4k-vivid-125-cm-50-inch-ultra-hd-4k-led-smart-tizen-tv-ua50due70b---2024-edition/p/494410254",
              "mrp": "61900",
              "sellingPrice": "43990",
              "discount": "29%(₹17,910)",
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": "10_percent_Instant_Bank_Discount",
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Supported Apps: NetFlix, Prime Video, Samsung TV Plus, Disney + Hotstar</li>\n<li>Operating System: Tizen</li>\n<li>Resolution: 3840 x 2160 4K Ultra HD</li>\n<li>Connectivity: 3 HDMI and 1 USB Ports</li>\n<li>Sound Output (RMS): 20 Watt </li>\n<li>Refresh Rate: 50 Hz</li>",
              "skuId": "494410254",
              "masterCategory": {
                "code": "S101812",
                "name": "Televisions",
                "url": "/televisions/c/S101812",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "UA50DUE70BKLXL",
              "numberOfReviews": 0,
              "numberOfRatings": 0,
              "averageRating": 0.0,
              "fullReviewUrl": null
            },
            {
              "name": "Samsung Crystal 4K Vivid 163 cm (65 inch) Ultra HD (4K) LED Smart Tizen TV  (UA65DUE70B) - 2024 Edition ",
              "imageUrl": "/medias/SAMSUNG-65DUE70B-LED-TVs-494410241-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w4NzgxM3xpbWFnZS9qcGVnfGltYWdlcy9oNzgvaDhiLzEwMTI5MzE4MzE0MDE0LmpwZ3xkZjI4ODdiNTQ4MDAzZDQwNTZiMzE4YzZjNWI0NTE5ZjdhMjZmYTE3NmFkNmVjODdkOTYxZTA3MjIyYjQ3Nzhl",
              "altText": "Samsung Crystal 4K Vivid 163 cm (65 inch) Ultra HD (4K) LED Smart Tizen TV  (UA65DUE70B) - 2024 Edition ",
              "url": "/samsung-crystal-4k-vivid-163-cm-65-inch-ultra-hd-4k-led-smart-tizen-tv-ua65due70b---2024-edition-/p/494410241",
              "mrp": "94900",
              "sellingPrice": "67990",
              "discount": "28%(₹26,910)",
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": "10_percent_Instant_Bank_Discount",
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Supported Apps: NetFlix, Prime Video, Samsung TV Plus, Disney + Hotstar</li>\n<li>Operating System: Tizen</li>\n<li>Resolution: 3840 x 2160 4K Ultra HD</li>\n<li>Connectivity: 3 HDMI and 1 USB Ports</li>\n<li>Sound Output (RMS): 20 Watt </li>\n<li>Refresh Rate: 50 Hz</li>",
              "skuId": "494410241",
              "masterCategory": {
                "code": "S101812",
                "name": "Televisions",
                "url": "/televisions/c/S101812",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "UA65DUE70BKLXL",
              "numberOfReviews": 0,
              "numberOfRatings": 0,
              "averageRating": 0.0,
              "fullReviewUrl": null
            },
            {
              "name": "Samsung Wondertainment 80 cm (32 Inch) Smart HD Ready TV, UA32T4340BKXXL",
              "imageUrl": "/medias/Samsung-UA32T4340BKXXL-Smart-Television-492403650-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyNDk1NnxpbWFnZS9qcGVnfGltYWdlcy9oNDcvaDE3Lzk4NDIyMDUxMzA3ODIuanBnfDljNDA4NjY5ZmYwYjNmMTBlMmYwZGEwODNkMTk5M2ZkMDc5MTgzZTAyY2VmNWYwMjJmYWNlZmEwNzBkNmYyZjI",
              "altText": "Samsung Wondertainment 80 cm (32 Inch) Smart HD Ready TV, UA32T4340BKXXL",
              "url": "/samsung-wondertainment-80-cm-32-inch-smart-hd-ready-tv-ua32t4340bkxxl/p/492403650",
              "mrp": "22900",
              "sellingPrice": "15990",
              "discount": "30%(₹6,910)",
              "deal": false,
              "inStock": true,
              "hasPP": true,
              "teaserType": "Flat 5% off on HDFC, SBI card",
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>1 Year Comprehensive Warranty on Product and 1 Year Additional warranty on Panel</li><li>Supported Apps: Prime Video, Hotstar, Netflix, Zee5 and many more, PC Mode, Universal Guide, Web Browser, Screen Mirroring</li><li>Operating System: Tizen</li><li>Resolution: 1366 x 768 (HD)</li> <li>Connectivity: 2 HDMI & 2 USB Ports</li><li>Sound Output (RMS): 20 Watt</li> <li>Refresh Rate: 60 Hz</li><li>Get additional 1 year comprehensive warranty (valid till 30th Nov 2022)</li>",
              "skuId": "492403650",
              "masterCategory": {
                "code": "S101812",
                "name": "Televisions",
                "url": "/televisions/c/S101812",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "UA32T4340BKXXL",
              "numberOfReviews": 9,
              "numberOfRatings": 71,
              "averageRating": 4.8,
              "fullReviewUrl": null
            },
            {
              "name": "LG 80 cm (32 inch) HD Ready LED Smart TV, 32LM560",
              "imageUrl": "/medias/LG-32-HD-Smart-LED-TV-32LM560-491898016-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wxMDA3MDd8aW1hZ2UvanBlZ3xpbWFnZXMvaGU1L2hhMy85NDQwNjM1ODEzOTE4LmpwZ3xhODFmMzRkZDk0N2IzM2I2NDhkMzYzZjUyYWEwZTIwYWI2ZTQ5MjE4MjE3NTY1Yzk4ZDE1NDQ0ZmVkOTIzOTEw",
              "altText": "LG 80 cm (32 inch) HD Ready LED Smart TV, 32LM560",
              "url": "/lg-80-cm-32-inch-hd-ready-led-smart-tv-32lm560/p/491898016",
              "mrp": "21990",
              "sellingPrice": "17340",
              "discount": "21%(₹4,650)",
              "deal": false,
              "inStock": true,
              "hasPP": true,
              "teaserType": "Flat 10% Instant Bank Discount",
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Resolution: HD (1366 x 720p)</li>\n<li>Display: Active HDR</li>\n<li>Dynamic Color Enhancer</li>\n<li>Smart TV features: Multi Tasking, You Tube, Netflix, Prime Video, Hotstar</li>\n<li>Connectivity: 2 HDMI ports, 1 USB port</li>\n<li>Sound: 10 Watts Output</li>",
              "skuId": "491898016",
              "masterCategory": {
                "code": "S101812",
                "name": "Televisions",
                "url": "/televisions/c/S101812",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "32LM560BPTC",
              "numberOfReviews": 0,
              "numberOfRatings": 0,
              "averageRating": 0.0,
              "fullReviewUrl": null
            },
            {
              "name": "TCL 32 Full HD Smart Android TV, 32S5403AF",
              "imageUrl": "/medias/TCL-32S5403AF-FHD-Smart-TV-493841915-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w3NDExN3xpbWFnZS9qcGVnfGltYWdlcy9oOWIvaDU0LzEwMDA0MDc4MDY3NzQyLmpwZ3wxMGIwZjRjYWMyNWM3ZjA1NzI1N2Y0ZjMzYzhjZGNmOGVhMjE1YjFjYzJkNDA1NGNhMTdkMWZjYThhMjk1ZDVi",
              "altText": "TCL 32 Full HD Smart Android TV, 32S5403AF",
              "url": "/tcl-32-full-hd-smart-android-tv-32s5403af/p/493841915",
              "mrp": "20990",
              "sellingPrice": "13490",
              "discount": "36%(₹7,500)",
              "deal": false,
              "inStock": true,
              "hasPP": false,
              "teaserType": "Flat 10% Instant Bank Discount",
              "preOrderEnabled": false,
              "preOrderDetails": null,
              "summary": "<li>Supported Apps: Google Play Store, YouTube, Google Play Games, Google Play Movies & TV, Chromcast, Netflix, Media Center</li>\n<li>Operating System: Android TV (Google Assistant)</li>\n<li>Resolution: Full HD (1920 x 1080)</li>\n<li>Connectivity: 2 HDMI ports, 1 USB ports</li>\n<li>Sound: 24 Watts, Dolby Audio</li>\n<li>Refresh Rate: 60 Hz</li>",
              "skuId": "493841915",
              "masterCategory": {
                "code": "S101812",
                "name": "Televisions",
                "url": "/televisions/c/S101812",
                "description": null,
                "image": null,
                "parentCategoryName": null,
                "sequence": 0
              },
              "productModelName": "32S5403AF",
              "numberOfReviews": 5,
              "numberOfRatings": 56,
              "averageRating": 4.7,
              "fullReviewUrl": null
            }
          ]
        }
      ]

      const slideNumberThree_data = mySlides[0].data;
      const slideNumberFour_data = mySlides[1].data;
      const slideNumberFive_data = mySlides[2].data;

  return (

    <Flex w={'100%'} >

    <Flex w={'100%'} justifyContent={'center'} alignItems={'center'} direction={'column'} gap={'5px'}>
       <Flex w={'100%'} bg={'#F9F9F9'} justifyContent={'center'} fontWeight={'500'}>
        <Flex justifyContent={'left'} w={'95%'} p={'20px 0px'}  gap={'10px'}>
                <Text>Stock clearance Sale | Monitors starting from Rs.3299</Text>
                <Button borderRadius={'revert'} fontSize={'xs'} color={'white'} bg={'#003380'}size={'sm'} p={'0px 10px'} _hover={{bg:'3003380', color:'white'}}>View All</Button>
            </Flex>
       </Flex>

        <Flex w={'100%'}   justifyContent={'center'} alignItems={'center'} >
         <CarouselWithMultiSlides multiSlidesData={slideNumberThree_data} />
        </Flex>


        <Flex w={'100%'} bg={'#F9F9F9'} justifyContent={'center'} fontWeight={'500'}>
        <Flex justifyContent={'left'} w={'95%'} p={'20px 0px'} gap={'10px'} >
                <Text>Best Selling Audio Accessories</Text>
                <Button borderRadius={'revert'} fontSize={'xs'} color={'white'} bg={'#003380'}size={'sm'} p={'0px 10px'} _hover={{bg:'3003380', color:'white'}}>View All</Button>
            </Flex>
       </Flex>

        <Flex w={'100%'}   justifyContent={'center'} alignItems={'center'} >
         <CarouselWithMultiSlides multiSlidesData={slideNumberFour_data} />
        </Flex>

        <Flex w={'100%'} bg={'#F9F9F9'} justifyContent={'center'} fontWeight={'500'}>
        <Flex justifyContent={'left'} w={'95%'} p={'20px 0px'} gap={'10px'} >
                <Text>Limited Time Offers on Televisions</Text>
                <Button borderRadius={'revert'} fontSize={'xs'} color={'white'} bg={'#003380'}size={'sm'} p={'0px 10px'} _hover={{bg:'3003380', color:'white'}}>View All</Button>
            </Flex>
       </Flex>

        <Flex w={'100%'}   justifyContent={'center'} alignItems={'center'} >
         <CarouselWithMultiSlides multiSlidesData={slideNumberFive_data} />
        </Flex>



    </Flex>    
</Flex>
   
  )
}

export default SectionThree